/* 《递补》首段审阅原型。所有页面、人员、文件与联络均为本地虚构内容。 */
(() => {
  'use strict';
  const KEY = 'dibu-preview-v21-1';
  const $ = (selector) => document.querySelector(selector);
  const escape = (value = '') => String(value).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const defaultState = {
    storyRevision:3, entered:false, openingClosed:false, activeApp:'browser', step:0,
    form:{rank:'',program:'',camp:'',file:'',ack:false}, submitted:false, error:'',
    note:'9月22日\n\n', checklist:{info:false,proof:false,july:false,notice:false}, memoEggSeen:false,
    selectedMail:'invitation', readMails:['invitation'], folder:'application', savedFiles:[],
    tabs:[{history:['form'],index:0}], activeTab:0, transcriptOpen:false, recoveryAnswer:'',savedAnswer:false,
    forumViewed:false, rankViewed:false, sourceNoticeSent:false, zhaoAdded:false, zhaoConversationStarted:false, zhaoQuestionStage:0, zhaoMessages:[], zhaoTyping:false, profileViewed:false, projectRead:false, memorialRead:false,
    lzyPrompted:false, lzyBatchAsked:false, lzyIdentityAsked:false, identityConclusion:'', identityReported:false, rosterCorrected:false,
    ncutQuery:'', campusKey:'ningchuan', campusQuery:'', campusArticleId:'', campusServiceKey:'', campusAccessGranted:false, campusAccessProject:false, campusAccessMemorial:false, progressCandidate:'', ncutProjectViewed:false, ncutMemorialViewed:false,
    survey:{answers:Array(10).fill(0),result:'',versions:0},
    assessmentOpened:false, oldAttachmentOpened:false, oldAttachmentSaved:false,
    tangInquiryPending:false, tangAsked:false, oldAttachmentCorrected:false,
    archiveVisited:false, archiveUrlSaved:false
  };
  // A shared preview link can always start from the authored opening without
  // changing the normal site's saved-progress behavior.
  const freshPreview = new URLSearchParams(location.search).get('fresh') === '1';
  if(freshPreview){try{localStorage.removeItem(KEY);}catch{}}
  let state;
  try { const loaded = JSON.parse(localStorage.getItem(KEY) || 'null'); state = loaded ? {...defaultState,...loaded,form:{...defaultState.form,...loaded.form},checklist:{...defaultState.checklist,...loaded.checklist},survey:{...defaultState.survey,...loaded.survey,answers:Array.isArray(loaded.survey?.answers)?loaded.survey.answers.slice(0,10).concat(Array(10).fill(0)).slice(0,10):Array(10).fill(0)}} : structuredClone(defaultState); }
  catch { state = JSON.parse(JSON.stringify(defaultState)); }
  // v3 changes the story timeline. Personal notes, checkmarks and saved copies remain;
  // the narrated application session begins again at the revised opening.
  if(state.storyRevision!==3){state={...state,storyRevision:3,entered:false,openingClosed:false,activeApp:'browser',step:0,form:{...defaultState.form},submitted:false,error:'',selectedMail:'invitation',readMails:['invitation'],tabs:[{history:['home'],index:0}],activeTab:0,survey:structuredClone(defaultState.survey)};}
  // Preserve progress from the earlier single-code version: a previously verified
  // session had already been allowed to read both historical documents.
  if(state.campusAccessGranted){state.campusAccessProject=true;state.campusAccessMemorial=true;}
  // Typing is a transient visual cue; a refreshed session never remains stuck waiting.
  if(state.zhaoTyping)state.zhaoTyping=false;
  if(state.tangInquiryPending)state.tangInquiryPending=false;
  if(state.folder==='reference')state.folder='application';
  if(freshPreview){try{history.replaceState(null,'',location.pathname);}catch{}}
  // The old default text is migrated only when it is unchanged. Player notes are never rewritten.
  const oldDefaultNote='9月22日\n\n□ 确认申请信息\n□ 补交成绩及排名证明\n□ 核对七月营期记录\n□ 查看后续通知\n';
  if(state.note===oldDefaultNote)state.note=defaultState.note;
  let toastTimer, activeDocument;
  function releaseDocument(){if(activeDocument?.temporary)URL.revokeObjectURL(activeDocument.pdf);activeDocument=null;}
  const checklistItems=[['info','补交项目说明'],['notice','完成问卷并查看接收进度'],['july','核对七月活动回执'],['proof','留存候补进度副本']];
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{toast('浏览器未允许本地保存，请保持此页面打开。');}}
  const iconPaths = {
    browser:'<circle cx="12" cy="12" r="9" fill="#1c94d4"/><path d="M3 13c5-7 12-9 17-4-1-6-10-9-15-3-2 2-3 5-2 7" fill="#62c1d3"/><path d="M4 14c3 6 12 9 17 1-6 4-11 1-11-3-3 0-5 1-6 2" fill="#1178ba"/>',
    folder:'<path d="M2 6a2 2 0 0 1 2-2h5l2 2h9a2 2 0 0 1 2 2v11H2z" fill="#e3b557"/><path d="M2 9h20v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2z" fill="#f2cc72"/>',
    mail:'<rect x="2" y="4" width="20" height="16" rx="2" fill="#398dca"/><path d="m3 5 9 8 9-8" fill="none" stroke="#dceffd" stroke-width="1.5"/><path d="m3 19 7-7m11 7-7-7" stroke="#ffffff55" fill="none"/>',
    chat:'<path d="M15 3C8 0 1 4 1 10c0 3 2 5 4 6l-1 4 5-3h2c-1-5 2-8 7-9 0-2-1-4-3-5" fill="#29b65d"/><path d="M22 14c0-4-4-6-7-6s-7 2-7 6 3 6 7 6h2l4 3-1-4c1-1 2-3 2-5" fill="#39c771"/><circle cx="7" cy="8" r="1" fill="#fff"/><circle cx="12" cy="8" r="1" fill="#fff"/><circle cx="13" cy="13" r="1" fill="#fff"/><circle cx="18" cy="13" r="1" fill="#fff"/>',
    note:'<path d="M5 2h15v20H5z" fill="#effaff" stroke="#479bc7"/><path d="M8 7h9M8 11h9M8 15h9M8 19h6" stroke="#75adcb"/><path d="M3 5h4M3 9h4M3 13h4M3 17h4" stroke="#4e7b9c" stroke-width="2"/>',
    document:'<path d="M5 2h10l5 5v15H5z" fill="#fff" stroke="#b6c8d5"/><path d="M15 2v6h5M8 12h9M8 16h9" fill="none" stroke="#9fb4c4"/><path d="M8 19h6" stroke="#c0cdd8"/>',
    recorder:'<rect x="5" y="2" width="14" height="20" rx="2" fill="none" stroke="currentColor" stroke-width="1.3"/><rect x="8" y="5" width="8" height="4" rx="1" fill="currentColor" opacity=".3"/><circle cx="12" cy="14" r="2.7" fill="none" stroke="currentColor"/><path d="M8 19h8" stroke="currentColor"/>',
    windows:'<path fill="#4286b4" d="M2 3h9v9H2zm11 0h9v9h-9zM2 14h9v9H2zm11 0h9v9h-9z"/>'
  };
  function icon(name,cls=''){return `<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true">${iconPaths[name]||iconPaths.document}</svg>`;}
  function crest(){return '<svg class="crest" viewBox="0 0 72 72" aria-hidden="true"><circle cx="36" cy="36" r="32" fill="none" stroke="currentColor" stroke-width="1.5"/><circle cx="36" cy="36" r="26" fill="none" stroke="currentColor" stroke-width=".8"/><path d="M19 39h34M24 34l12-9 12 9M27 35v14m9-14v14m9-14v14M22 49h28" fill="none" stroke="currentColor" stroke-width="2"/><path d="M16 43q2 13 15 16m25-16q-2 13-15 16" fill="none" stroke="currentColor"/><text x="36" y="19" text-anchor="middle" font-size="7" fill="currentColor" font-family="serif">HENGCHUAN</text><text x="36" y="60" text-anchor="middle" font-size="6" fill="currentColor" font-family="serif">1958</text></svg>';}
  const files = {
  "application": [
    {
      "id": "resume",
      "name": "陈言_个人简历.pdf",
      "date": "2026/09/18 16:42"
    },
    {
      "id": "grade-draft",
      "name": "成绩及排名证明_自助导出.pdf",
      "date": "2026/09/18 10:06"
    },
    {
      "id": "grade-certified",
      "name": "成绩及排名证明_教务盖章.pdf",
      "date": "2026/09/19 14:28"
    },
    {
      "id": "statement",
      "name": "个人陈述.pdf",
      "date": "2026/09/18 17:12"
    },
    {
      "id": "application-log",
      "name": "项目说明.pdf",
      "date": "2026/09/22 08:10"
    }
  ],
  "july": [
    {
      "id": "ticket",
      "name": "往返行程单.pdf",
      "date": "2026/07/13 21:14"
    },
    {
      "id": "camp-photo",
      "name": "研究院北楼_报到日.jpg",
      "date": "2026/07/11 09:32",
      "photo": true,
      "text": "照片备注：报到当天，研究院北楼。\n保存日期：2026年7月11日。\n\n建筑门口挂着夏令营报到处的指示牌。"
    },
    {
      "id": "camp-receipt",
      "name": "营期活动确认回执.pdf",
      "date": "2026/07/13 16:40"
    },
    {
      "id": "july-note",
      "name": "七月旧笔记.pdf",
      "date": "2026/07/13 20:36"
    },
    {
      "id": "july-summary",
      "name": "营期活动摘要_个人留存.pdf",
      "date": "2026/07/14 10:12"
    }
  ],
  "reference": [
    {
      "id": "ningchuan-project",
      "name": "轮式巡检平台阶段测试_宁川理工大学新闻网.pdf",
      "date": "2022/11/18 10:30"
    },
    {
      "id": "ningchuan-memorial",
      "name": "林知远同学追思会_宁川理工大学新闻网.pdf",
      "date": "2024/06/09 14:10"
    }
  ]
};
  for(const group of Object.values(files))for(const file of group){
    const asset=window.DIBU_DOCUMENTS[file.id];
    if(asset){Object.assign(file,asset);file.name=file.name.replace(/\.txt$/i,'.pdf');}
  }
  const taskAttachments=[Object.assign({id:'old-project-example',name:'项目经历填写示例.pdf',date:'2026/09/22 10:18',servedAt:'2026年9月22日 10:18',recordDate:'2023年7月16日',recordNo:'HC23-XLY-B17-042'},window.DIBU_DOCUMENTS['old-project-example']||{})];
  const steps=['补充说明','本人信息','申请材料','确认提交'];
  const campuses={
    jiangnan:{name:'江南信息大学',english:'JIANGNAN UNIVERSITY OF INFORMATION',domain:'www.jniu.example',accent:'#315d91',accentDark:'#23456c',lead:'信息工程学院启动新学期科研训练计划',leadText:'面向高年级学生开放数据处理、智能系统与通信工程等方向的校级项目申报。',notices:['2026 年秋季学期选课补退选安排','图书馆南馆夜间开放时间调整','关于开展学生证集中补办的通知'],schools:['信息工程学院举行新生专业导学','网络空间安全学院发布助教名单','校友创新论坛报名通知'],services:['教务系统','科研项目申报','图书资源','学生事务'],serviceIntro:'面向本科生的课程、项目和校园事务办理入口。'},
    ningchuan:{name:'宁川理工大学',english:'NINGCHUAN INSTITUTE OF TECHNOLOGY',domain:'www.ncut.example',accent:'#1e7255',accentDark:'#18543f',lead:'学校启动 2026 年秋季学期实验室安全检查',leadText:'各学院将完成设备台账复核、实验室开放预约与新生安全教育工作。',notices:['关于办理 2026 年秋季学期教材补订的通知','图书馆北区自习区开放时间调整','2026 年学生社团纳新安排'],schools:['自动化学院开展新生专业导学','机械学院团队获智能制造竞赛奖项','计算机学院公布课程助教名单'],services:['教务与学籍','科研资料库','图书资源','校内信息服务'],serviceIntro:'实验室预约、历史科研资料和学生事务的统一服务入口。'},
    songling:{name:'松岭大学',english:'SONGLING UNIVERSITY',domain:'www.slu.example',accent:'#8a4d36',accentDark:'#663425',lead:'松岭大学发布本科生创新实践项目中期检查安排',leadText:'各项目组将围绕研究计划、原始材料与阶段成果完成线上归档。',notices:['2026 年秋季学期研究生奖助工作提示','校医院体检预约服务说明','体育场馆国庆期间开放安排'],schools:['自动化系组织嵌入式系统工作坊','人文学院启动田野资料整理计划','实验中心更新仪器预约规则'],services:['实践项目管理','田野资料中心','图书资源','校园健康'],serviceIntro:'服务内容围绕社会实践、创新项目和田野资料整理展开。'},
    lanjiang:{name:'岚江工业大学',english:'LANJIANG UNIVERSITY OF TECHNOLOGY',domain:'www.ljut.example',accent:'#6c4d81',accentDark:'#49345d',lead:'岚江工业大学举行新学年教学科研工作会议',leadText:'会议梳理实验教学、学生创新项目和跨学院公共平台的秋季安排。',notices:['2026 级新生学籍电子注册提示','校园网账号服务调整公告','关于补办校园一卡通的安排'],schools:['自动化学院开放控制实验室参观预约','经管学院发布数据分析训练营通知','学生发展中心启动简历咨询服务'],services:['教学运行','控制实验室','就业服务','校园一卡通'],serviceIntro:'教学运行、实验预约和毕业生就业服务的办事入口。'},
    dongpu:{name:'东浦科技大学',english:'DONGPU UNIVERSITY OF SCIENCE AND TECHNOLOGY',domain:'www.dput.example',accent:'#2d6d7a',accentDark:'#20535d',lead:'东浦科技大学完成暑期实验室设备维护与校准',leadText:'相关设备将于秋季学期按预约制度面向教学与学生项目开放。',notices:['2026 年秋季学期教材发放安排','研究生迎新志愿者招募通知','校园巴士运行时刻更新'],schools:['智能制造学院开展课程项目展示','计算学院举办开源软件交流会','校团委公布社团年度注册名单'],services:['设备预约','开源项目','图书资源','校园巴士'],serviceIntro:'智能制造、计算实验和校园运行服务的综合入口。'},
    beihe:{name:'北河大学',english:'BEIHE UNIVERSITY',domain:'www.bhu.example',accent:'#476d43',accentDark:'#315035',lead:'北河大学发布秋季学期本科教学运行说明',leadText:'学校将持续完善课程评价、实践教学与学生事务办理服务。',notices:['关于开展 2026 年困难生认定的通知','北河讲坛第八期活动预告','教学楼空调检修安排'],schools:['电子学院组织信号处理专题报告','数学学院更新竞赛培训安排','图书馆开展馆藏资源使用培训'],services:['教学管理','北河讲坛','图书资源','实验室安全'],serviceIntro:'教学安排、公开讲坛和实验室使用的综合信息服务。'}
  };
  const candidateCampus={周亦成:'jiangnan',林知远:'ningchuan',许澄:'songling',赵可宁:'lanjiang',顾宁:'dongpu',蒋思齐:'beihe',陈言:'lanjiang'};
  const candidateRecords={
    周亦成:{category:'信息工程学院 · 2026-08-31',title:'周亦成同学暑期志愿服务时长确认名单',text:'名单用于学院团学活动统计，异议请在公示期内向学生工作办公室反馈。'},
    林知远:{category:'自动化学院 · 2022-06-24',title:'林知远同学课程项目结项材料归档提示',text:'课程实践材料按届别归档，查询请联系实验教学中心。'},
    许澄:{category:'松岭大学团委 · 2026-07-08',title:'许澄同学社会实践项目结项公示',text:'公示内容为实践项目参与信息，与学籍和招生事项无关。'},
    赵可宁:{category:'自动化学院 · 2026-09-03',title:'赵可宁同学参加创新训练项目成员变更备案',text:'项目成员变更已完成院内登记，项目材料由指导教师统一留存。'},
    顾宁:{category:'智能制造学院 · 2026-06-19',title:'顾宁同学获校级学业发展奖学金拟推荐',text:'拟推荐名单按学院工作程序公示，相关证明材料由学院存档。'},
    蒋思齐:{category:'电子学院 · 2026-08-27',title:'蒋思齐同学实验室安全培训完成记录',text:'培训记录用于实验室预约资格核验，请勿作为其他用途的证明。'},
    陈言:{category:'自动化学院 · 2026-09-06',title:'陈言同学本科生科研训练计划申报受理',text:'项目申报材料已进入院系初审流程，结果以学院通知为准。'}
  };
  const campusArticleData={
    jiangnan:[
      {id:'jn-course',category:'教务通知 · 2026-09-12',title:'江南信息大学秋季学期课程调整说明',summary:'部分实践课程调整至信息楼机房，选课系统中的课表将同步更新。',body:'教务处发布秋季学期课程调整说明。信息工程、数据科学和网络安全方向的部分实践课程将使用新机房，学生可在课表详情中查看教室与分组安排。调整只影响上课地点和分组，不影响原有成绩认定。'},
      {id:'jn-lab',category:'科研动态 · 2026-08-29',title:'数据智能实验室开放本科生项目申请',summary:'实验室面向高年级学生开放数据清洗、可视化和边缘计算方向的训练项目。',body:'数据智能实验室公布秋季开放项目清单。本科生可以个人或组队提交申请，项目周期为八周，结项材料包括实验记录、代码说明和阶段汇报。具体安排由信息工程学院教学秘书统一收取。'},
      {id:'jn-forum',category:'校园文化 · 2026-06-25',title:'校友创新论坛公布本年度分享嘉宾',summary:'论坛将围绕从课堂项目到产业实践的路径展开，报名入口位于校友工作栏目。',body:'江南信息大学校友创新论坛将于六月底举行。信息服务、智能终端和公共数据三个分会场分别邀请毕业校友分享工作经验，学生可凭校园账号预约旁听。'}
    ],
    ningchuan:[
      {id:'nc-safety',category:'实验室安全 · 2026-09-12',title:'自动化学院秋季实验室开放与安全培训安排',summary:'新生须完成线上培训和设备识别测试后，方可预约控制实验室。',body:'自动化学院公布秋季实验室开放安排。培训包括电气安全、急停装置识别和设备借用登记，培训记录由实验教学中心保存。需要补做测试的同学可在服务大厅提交预约。'},
      {id:'nc-library',category:'图书馆通知 · 2026-09-05',title:'北区自习区开放时间与座位预约调整',summary:'北区自习区试行分时段预约，历史借阅记录不受影响。',body:'图书馆北区自习区自九月起试行分时段预约。读者可在图书馆服务平台选择座位，离开前请主动结束预约，连续多次占座将收到提醒。'},
      {id:'nc-club',category:'学生工作 · 2026-08-26',title:'2026年学生社团纳新安排公布',summary:'社团集中展示将在体育馆东厅举行，报名信息由各社团自行维护。',body:'学生工作处公布本年度社团纳新安排。集中展示期间，各社团将介绍活动方向、值班时间和报名方式，新成员信息由社团指导教师负责审核。'},
      {id:'nc-project',category:'科研动态 · 2022-11-18',title:'自动化学院团队完成轮式巡检平台阶段测试',summary:'轮式巡检平台多传感器定位课程项目完成阶段验证，相关材料作为本科实践教学案例留存。',body:'自动化学院“轮式巡检平台多传感器定位”课程项目日前完成阶段测试。项目围绕轮速计、惯性测量与视觉定位的联合校正开展设计验证。项目由2020级自动化专业林知远负责统筹，团队成员分工完成传感器标定、数据采集、路径复现和误差记录。结项说明显示，原始运行日志、答辩问答摘要和语音片段曾被加密转存至联合教学案例库，封存标签为 JI-22-014。转存授权明确限定为教学复盘，不得用于选拔、评价或对外身份展示。项目指导教师介绍，相关材料将作为本科实践教学案例留存。',access:'internal'},
      {id:'nc-memorial',category:'学院消息 · 2024-06-09',title:'自动化学院举行林知远同学追思会',summary:'学院发布纪念活动公告，教学资料将按既有规范归档。',body:'6月8日，自动化学院师生举行林知远同学追思会。公告确认林知远为我校自动化学院2020级本科生，曾参与轮式巡检平台多传感器定位课程项目，并于2023年被衡川大学先进系统研究院录取、完成入学。学院在整理遗留项目资料时注明，联合教学案例库中的 JI-22-014 转存记录仍处于保留状态。2026年9月21日，该记录新增一条外部读取回执：申请目的为“招生材料一致性复核”，发起单位为衡川大学先进系统研究院。学院表示，这项读取不在宁川校内办理范围内，将向联合案例库管理方核实。为尊重家属意愿，学院未公布其他个人信息。',access:'internal'}
    ],
    songling:[
      {id:'sl-practice',category:'实践项目 · 2026-09-08',title:'松岭大学创新实践项目中期检查开始',summary:'各项目组需提交原始记录、阶段成果和经费使用说明。',body:'创新实践项目中期检查采用线上归档和现场抽查相结合的方式。项目负责人须在系统中上传原始记录，指导教师确认后才可进入结项阶段。未按时提交的项目将收到补正提醒。'},
      {id:'sl-field',category:'人文学院 · 2026-07-08',title:'田野资料整理工作坊开放预约',summary:'工作坊介绍访谈转写、匿名化处理和资料目录编制方法。',body:'人文学院资料中心面向全校开放田野资料整理工作坊。参加者可以带来自己的课程调研材料，工作人员会演示录音转写、文件命名和匿名化处理流程。'},
      {id:'sl-health',category:'校园生活 · 2026-06-25',title:'校医院发布暑期体检预约提示',summary:'体检预约按时间段开放，学生可在校园服务平台查询结果。',body:'校医院提醒师生按预约时段到场，体检报告将在完成复核后上传个人服务空间。近期就诊高峰集中在上午，建议提前准备校园卡和既往检查记录。'}
    ],
    lanjiang:[
      {id:'lj-control',category:'实验教学 · 2026-09-03',title:'控制实验室开放参观预约开始',summary:'自动化学院安排三场设备演示，介绍控制柜、运动平台和数据采集流程。',body:'控制实验室将面向本科生开放参观。每场活动包含设备演示和安全说明，参观者须在预约时填写学院、年级及紧急联系人。活动结束后可领取实验室使用手册。'},
      {id:'lj-career',category:'学生发展 · 2026-08-22',title:'学生发展中心启动秋季简历咨询服务',summary:'咨询服务覆盖简历结构、项目表述和面试准备，需提前在线预约。',body:'学生发展中心发布秋季咨询安排。每位同学可预约一次一对一修改和一次模拟面试，咨询记录只用于服务改进，不会写入学籍档案。'},
      {id:'lj-card',category:'办事服务 · 2026-06-30',title:'校园一卡通补办窗口调整至东门服务厅',summary:'旧卡挂失、照片核验和余额转移均可在服务厅办理。',body:'信息化建设处提醒，一卡通补办窗口自七月起调整至东门服务厅。办理时请携带有效校园证件，余额转移一般在一个工作日内完成。'}
    ],
    dongpu:[
      {id:'dp-maint',category:'设备管理 · 2026-08-30',title:'暑期实验室设备维护清单公布',summary:'校级平台完成校准的设备将按预约制度重新开放。',body:'实验中心公布设备维护清单。涉及激光测距、工业相机和机械臂的设备已完成校准，秋季学期开放时间将按学院课程和学生项目优先级排定。'},
      {id:'dp-open',category:'计算学院 · 2026-08-16',title:'开源软件交流会征集学生分享',summary:'交流会欢迎分享课程项目、工具链配置和可复用代码。',body:'计算学院将举办开源软件交流会。分享内容应包含项目背景、使用许可和复现说明，报名材料由学院学生工作组统一收集。'},
      {id:'dp-bus',category:'校园服务 · 2026-06-22',title:'校园巴士暑期运行时刻更新',summary:'周末线路合并，晚间末班车时间保持不变。',body:'后勤服务中心更新暑期巴士时刻。工作日线路按照教学楼、实验中心和宿舍区顺序运行，周末两条支线合并，乘车时请留意站牌变化。'}
    ],
    beihe:[
      {id:'bh-signal',category:'电子学院 · 2026-08-27',title:'信号处理专题报告开放报名',summary:'报告介绍噪声环境下的信号恢复方法，报名面向全校本科生。',body:'电子学院邀请校外研究人员举办信号处理专题报告。报告包含算法演示和问答环节，报名成功后可在讲坛页面下载讲义和参考资料。'},
      {id:'bh-math',category:'数学学院 · 2026-08-12',title:'秋季竞赛培训课程安排更新',summary:'培训覆盖数学建模、算法基础和论文写作三个模块。',body:'数学学院公布秋季竞赛培训课程安排。新生可先参加基础模块，再根据兴趣选择建模或算法方向，课程考勤只用于统计培训完成情况。'},
      {id:'bh-library',category:'图书馆 · 2026-06-24',title:'馆藏资源使用培训开放预约',summary:'培训介绍校外访问、文献传递和个人书目管理功能。',body:'图书馆开展馆藏资源使用培训。参加者可以现场完成校外访问测试，并学习如何保存检索式和设置新书提醒。'}
    ]
  };
  function campus(){return campuses[state.campusKey]||campuses.ningchuan;}
  function routeLabel(route){if(route==='campusHome'||route==='campusSearch')return route==='campusSearch'?`${campus().name}搜索`:campus().name;return labels[route]||labels.blank;}
  const labels={home:'衡川大学先进系统研究院',form:'申请材料补充',dashboard:'研究生报考服务系统',departments:'申请院系开放查询',notice:'补充材料确认通知',status:'申请状态查询',result:'申请结果查询',rank:'方向接收进度',candidateSummary:'申请人履历摘要',questionnaire:'申请人情况与学习习惯问卷',assessment:'补充考核与材料复核',oldArchive:'先进系统研究院旧招生归档',followup:'夏令营活动记录确认',forum:'申请人交流区',profile:'林知远候补资格摘要',ningchuanHome:'宁川理工大学',ningchuanSearch:'宁川理工大学搜索',campusHome:'校园首页',campusSearch:'站内搜索',campusArticle:'文章详情',campusService:'办事服务',newsProject:'宁川理工大学项目报道',newsMemorial:'宁川理工大学纪念公告',lzyThread:'林知远站内会话',identityCheck:'记录与资料核对',login:'研究生报考服务系统',blank:'新标签页'};
  const paths={home:'https://admission.hcu.example/2027',form:'https://xspt.hcu.example/sstm/tm/application',dashboard:'https://xspt.hcu.example/sstm/tm/index',departments:'https://xspt.hcu.example/sstm/tm/opening',notice:'https://admission.hcu.example/2027/notices/0922',status:'https://xspt.hcu.example/sstm/tm/status',result:'https://xspt.hcu.example/sstm/tm/result',rank:'https://xspt.hcu.example/sstm/tm/progress',questionnaire:'https://admission.hcu.example/2027/questionnaire',assessment:'https://admission.hcu.example/2027/assessment/material-review',oldArchive:'https://archive.asri.hcu.example/admission/',followup:'https://xspt.hcu.example/sstm/tm/revisit/0922',forum:'https://admission.hcu.example/2027/community',profile:'https://admission.hcu.example/2027/community/candidates/HC-014',ningchuanHome:'https://www.ncut.example',ningchuanSearch:'https://www.ncut.example/search',campusHome:'',campusSearch:'',campusArticle:'',campusService:'',newsProject:'https://news.ncut.example/2022/1118/inspection-platform',newsMemorial:'https://news.ncut.example/2024/0609/lin-zhiyuan',lzyThread:'https://admission.hcu.example/2027/community/messages/LZY-014',identityCheck:'https://admission.hcu.example/2027/records/check',login:'https://xspt.hcu.example/logon',blank:''};
  function routePath(route){if(route==='campusHome')return `https://${campus().domain}`;if(route==='campusSearch')return `https://${campus().domain}/search`;return paths[route]||'';}
  function currentTab(){return state.tabs[state.activeTab]||state.tabs[0];}
  function currentRoute(){const tab=currentTab();return tab.history[tab.index];}
  function go(route){if(route==='assessment'&&state.survey.result!=='C'){route='questionnaire';toast('补充考核仅在问卷进入后续安排后开放。');}const tab=currentTab();if(currentRoute()!==route){tab.history=tab.history.slice(0,tab.index+1);tab.history.push(route);tab.index=tab.history.length-1;}if(route==='forum')state.forumViewed=true;if(route==='rank'){state.rankViewed=true;if(state.survey.result)state.checklist.notice=true;}if(route==='assessment')state.assessmentOpened=true;if(route==='oldArchive')state.archiveVisited=true;if(route==='profile')state.profileViewed=true;if(route==='newsProject'){state.projectRead=true;state.ncutProjectViewed=true;}if(route==='newsMemorial'){state.memorialRead=true;state.ncutMemorialViewed=true;}state.activeApp='browser';state.error='';save();render();}
  function toast(msg){const el=$('#toast');el.className='toast';el.textContent=msg;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.className='';el.textContent='';},3300);}
  function modal(content,extra='',label='资料详情'){releaseDocument();const root=$('#dialog-root');root.innerHTML=`<div class="dialog-backdrop"><section class="dialog ${extra}" role="dialog" aria-modal="true" aria-label="${label}"><button class="dialog-close" data-action="close-dialog" aria-label="关闭">×</button>${content}</section></div>`;root.querySelector('button')?.focus();}
  function closeDialog(){ releaseDocument();$('#dialog-root').innerHTML=''; if(!state.openingClosed){state.openingClosed=true;save();} }
  function opening(){modal(`<div class="opening-copy"><p>2026年9月22日。</p><p>你叫陈言，是自动化相关专业的大四学生。你已经取得本校推免资格，却还没有确定接收学校。</p><p>今年七月，你参加过衡川大学先进系统研究院的夏令营。那次申请没有带来确定的去向，你仍保留着通知、行程和准备过的材料。</p><p>今天上午，研究院发来补充考核邮件。邮件称，部分接收安排尚未确定，符合条件的申请人可以补交材料，继续等待递补机会。</p><p>你打开了邮件中的地址。</p></div>`,'opening-dialog','背景');}
  function home(){return `<div class="site-home"><header class="institute-head">${crest()}<div><div class="university">衡川大学</div><div class="institute-name">先进系统研究院</div></div></header><nav class="home-nav" aria-label="栏目"><div><span>研究院首页</span><span>院情介绍</span><span>师资队伍</span><span>科学研究</span><span>研究生招生</span><span>联系我们</span></div></nav><section class="home-main"><div class="home-eyebrow">GRADUATE ADMISSIONS · 2027</div><h1>2027 年研究生招生</h1><p class="home-lead">补充考核与候补进度查询</p><div class="home-callout"><div><strong>关于开展 2027 年研究生招生补充材料确认工作的通知</strong><p>请已收到邮件的申请人登录工作台，核对材料并查看后续安排。</p></div><button class="primary" data-action="enter">进入申请人工作台</button></div><section class="announcements"><h2>通知公告</h2><div class="announcement"><span>先进系统研究院 2027 年研究生招生补充材料确认工作安排</span><time>2026-09-22</time></div><div class="announcement"><span>2027 年接收推荐免试研究生有关事项说明</span><time>2026-09-08</time></div><div class="announcement"><span>研究生招生咨询方式更新</span><time>2026-06-10</time></div></section></section><footer class="home-footer">衡川大学先进系统研究院<br>研究生招生工作办公室</footer></div>`;}
  function masthead(){return `<header class="site-head">${crest()}<div><div class="university">衡川大学</div><div class="english">Hengchuan University</div></div><div class="mast-title">研究生报考服务系统</div></header>`;}
  function shell(content,login=false){return `${!login?'<div class="utility-bar"><span>你好，陈言！</span><button data-action="route" data-route="dashboard">返回首页</button><span class="sep">|</span><button data-action="account">账户信息</button><span class="sep">|</span><button data-action="route" data-route="login">登出</button></div>':''}${masthead()}${!login?'<div class="system-banner"><h1>2027 年研究生招生申请服务</h1></div>':''}${content}<footer class="system-footer">衡川大学研究生院 · 先进系统研究院招生办公室</footer>`;}
  function crumb(text,completion=false){const complete=completeCount();return `<div class="breadcrumbs"><span aria-hidden="true">⌂</span><button data-action="route" data-route="dashboard">首页</button><span>»</span><span>${text}</span>${completion?`<span class="completion">已完成${complete}步</span><span>（共${steps.length}步）</span>`:''}</div>`;}
  function stepDone(i){if(i===2)return !!state.form.file;if(i===3)return state.submitted;return true;}
  function completeCount(){return steps.filter((_,i)=>stepDone(i)).length;}
  function row(label,value,help='',required=false){return `<div class="form-row"><div class="form-label">${label}${required?'<span class="required">*</span>':''}</div><div>${value}</div><div class="field-help">${help}</div></div>`;}
  function field(label,id,value,help='',readonly=false){return `<div class="form-row"><label for="${id}">${label}${readonly?'':'<span class="required">*</span>'}</label><input id="${id}" ${readonly?'readonly':'data-field="'+id+'"'} value="${escape(value)}" ${state.submitted&&!readonly?'readonly':''} autocomplete="off"><div class="field-help">${help}</div></div>`;}
  function formContent(){const f=state.form;
    if(state.step===0)return `<h2>申请材料补充</h2><div class="form-text"><p>本次面向已参加七月夏令营、接收安排尚未确定的申请人开放。请先核对个人陈述版本，并补交一份项目说明。</p><p>补交材料只用于本轮招生审核；提交后会生成可保存的本人回执。</p></div><div class="info-note">需补充：<b>项目说明</b>。个人陈述已在申请材料中登记，无需重新填写。</div><div class="subtle-note">材料位于电脑的“文件 / 申请材料”。<button class="text" data-action="files-folder" data-folder="application">打开申请材料文件夹</button></div>`;
    if(state.step===1)return `<h2>本人信息</h2>${row('申请编号','HC2026-0922-071')}${row('姓名','陈言')}${row('本科院校','岚江工业大学')}${row('本科院系 / 专业','自动化学院 / 自动化')}${row('本轮状态','材料待补充')}<div class="info-note">本页信息来自七月申请记录。本轮不要求输入真实证件、手机号或密码。</div>`;
    if(state.step===2)return `<h2>补交项目说明</h2><div class="info-note">请从本机“申请材料”中选择《项目说明》。该文件应只陈述本人实际承担的工作。</div>${row('个人陈述','个人陈述.pdf','已登记版本：2026年9月18日')}${row('项目说明',f.file?`<span>${escape(findFile(f.file)?.name||'')}</span><br><button class="text small" data-action="picker" ${state.submitted?'disabled':''}>重新选择</button>`:`<button class="secondary" data-action="picker">选择本地文件</button>`,'从申请材料文件夹选择',true)}<p class="small muted">选择文件不会立刻提交；可先在弹窗中查看 PDF。</p>`;
    if(state.step===3)return `<h2>确认提交</h2>${state.submitted?'<div class="inline-success">材料补充已提交。请查看回执与邮箱中的后续安排。</div>':'<div class="info-note">请核对本次提交的材料。保存只保留草稿；正式提交后，材料进入本轮审核。</div>'}<ul class="review-list"><li><span>申请人</span><strong>陈言 / HC2026-0922-071</strong></li><li><span>个人陈述</span><strong>个人陈述.pdf（已登记）</strong></li><li><span>补交材料</span><strong>${escape(findFile(f.file)?.name||'待选择')}</strong></li></ul>${!state.submitted?`<label class="check-line" style="margin-top:23px"><input type="checkbox" data-field="ack" ${f.ack?'checked':''}>我确认项目说明由本人整理，内容与实际经历一致。</label>`:'<p class="small muted">提交时间：2026年9月22日 09:18<br>回执编号：RC-0922-071</p>'}${state.error?`<div class="inline-error" role="alert">${escape(state.error).replace(/\n/g,'<br>')}</div>`:''}`;
    switch(state.step){
    case 0:return `<h2>申请须知</h2><div class="form-text"><p>有意申请考生请查询接收学院通知，并按接收学院要求完成报名。</p><p>本次为已参加夏令营考生的补充材料确认。七月已登记的信息已导入，请重点核对学习信息、申请信息及上传材料。</p></div><div class="info-note">需补充：专业排名比例、申请方向、营期批次及盖章成绩证明。<br>材料要求与方向代码见 <button class="text" data-action="route" data-route="notice">《2027级推免补充考核材料确认通知》</button>。<br>营期批次请以本人留存的确认回执为准。</div><div class="subtle-note">申请材料位于电脑的“文件”中。<button class="text" data-action="files-folder" data-folder="application">打开申请材料文件夹</button><br>七月已有的材料无需重新办理，可使用本人留存文件核对。</div>`;
    case 1:return `<h2>基本信息</h2>${row('报名号','HC2026-0922-071')}${field('姓名','readonly-name','陈言','字库中没有的汉字用大写汉语拼音字母代替，中间无空格',true)}${field('姓名拼音','readonly-pinyin','ChenYan','按紧左原则，字母间不加任何字符',true)}${row('证件类型','居民身份证')}${row('证件号码','******************','已核验；本页不展示完整号码')}${row('出生日期','2005年','已从营期信息导入')}${row('性别','未公开')}${row('在校身份','本科在读')}${row('联系邮箱','chenyan@letter.example','已验证')}`;
    case 2:return `<h2>家庭主要成员</h2><div class="info-note">沿用七月已确认资料，本次无需补充家庭成员信息。</div>${row('家庭成员资料','已登记','仅本人及授权审核人员可查阅')}${row('紧急联系方式','已核验','本次材料确认不要求重新填写')}`;
    case 3:return `<h2>学习信息</h2><div class="info-note">请依据完整成绩及排名证明，填写专业排名比例。<br>比例计算方式：本人名次 ÷ 参与排名人数 × 100%。结果保留两位小数。</div>${row('本科院校','岚江工业大学')}${row('本科院系','自动化学院')}${row('本科专业','自动化')}${row('预计毕业年份','2027年')}${row('推免资格','已取得本校推荐资格')}${field('专业排名比例（%）','rank',f.rank,'填写百分数数值，不含“%”。例如 10.00。')}${row('核对材料','<button class="text" data-action="files-folder" data-folder="application">查看本地成绩及排名证明</button>','请核对名次及参与排名人数')}`;
    case 4:return `<h2>外语水平</h2>${row('语种','英语')}${row('考试类型','大学英语六级')}${row('成绩','568')}${row('证明材料','已核验','沿用七月提交记录')}`;
    case 5:return `<h2>计算机水平</h2>${row('编程语言','Python、C')}${row('说明','已完成本科相关课程')}${row('资料状态','已确认','本项无需补充')}`;
    case 6:return `<h2>学习和工作经历</h2>${row('起止时间','2023年09月 — 至今')}${row('学习经历','自动化专业本科在读')}${row('工作经历','无')}`;
    case 7:return `<h2>学术成果</h2>${row('公开发表论文','无')}${row('课程项目','移动平台轨迹跟踪')}${row('本人分工','数据整理与模型验证')}${row('成果材料','已上传项目说明','沿用夏令营申请材料')}`;
    case 8:return `<h2>奖励或处分（本科期间）</h2>${row('奖励记录','校级优秀学生奖学金')}${row('处分记录','无')}${row('材料状态','已核验')}`;
    case 9:return `<h2>申请信息</h2><div class="info-note">请按照本轮补充考核通知选择申请方向。营期批次可在七月活动确认回执中查找。<br><button class="text" data-action="route" data-route="notice">查看补充考核通知</button>　<button class="text" data-action="files-folder" data-folder="july">打开七月夏令营文件夹</button></div>${row('申请院系','先进系统研究院')}${row('招生年份','2027年')}${row('申请类型','推免生预报名')}${row('申请方向',`<select id="program" aria-label="申请方向" data-field="program" ${state.submitted?'disabled':''}><option value="">请选择申请方向</option><option value="0811/H01" ${f.program==='0811/H01'?'selected':''}>0811 / H01 · 智能控制</option><option value="0811/H03" ${f.program==='0811/H03'?'selected':''}>0811 / H03 · 复杂系统与人机交互</option><option value="0854/H02" ${f.program==='0854/H02'?'selected':''}>0854 / H02 · 电子信息</option></select>`,'以9月22日通知的开放方向为准',true)}${field('营期批次','camp',f.camp,'请按本人营期活动确认回执填写，保留连接符。')}${row('申请导师','考核后确认','本轮无需提前选择')}`;
    case 10:return `<h2>上传照片</h2><div class="info-note">已核验营期登记照片，无需重复上传。</div><div style="width:112px;height:145px;background:#e9f0f5;border:1px solid #dce5ed;display:flex;align-items:center;justify-content:center;color:#a0b2c0;font-size:36px;margin:25px">陈</div>${row('照片状态','已通过格式审核')}`;
    case 11:return `<h2>上传材料</h2><div class="info-note">请提交含成绩页、排名页及教务审核印章的完整证明。自助导出文件不能替代审核盖章版本。</div>${row('个人简历','陈言_个人简历.pdf','已登记')}${row('个人陈述','个人陈述.pdf','已更新至9月版本')}${row('成绩及排名证明',f.file?`<span>${escape(findFile(f.file)?.name||'')}</span><br><button class="text small" data-action="picker" ${state.submitted?'disabled':''}>重新选择</button>`:`<button class="secondary" data-action="picker">选择本地材料</button>`,'从陈言已整理的申请材料中选择',true)}<p class="small muted" style="line-height:1.9">已选附件会随最终提交一并交给招生办公室审核。<br>选择材料后仍可返回检查，不会立刻提交申请。</p>`;
    case 12:return `<h2>申请信息提交</h2>${state.submitted?'<div class="inline-success">申请材料已提交。请查看站内回执及邮箱中的后续安排。</div>':'<div class="info-note">请最后核对以下信息。保存只保留草稿；正式提交后，材料进入本轮审核。</div>'}<ul class="review-list"><li><span>申请人</span><strong>陈言 / HC2026-0922-071</strong></li><li><span>专业排名比例</span><strong>${f.rank?escape(f.rank)+'%':'待填写'}</strong></li><li><span>申请方向</span><strong>${escape(f.program)||'待选择'}</strong></li><li><span>营期批次</span><strong>${escape(f.camp)||'待填写'}</strong></li><li><span>成绩及排名证明</span><strong>${escape(findFile(f.file)?.name||'待选择')}</strong></li></ul>${!state.submitted?`<label class="check-line" style="margin-top:23px"><input type="checkbox" data-field="ack" ${f.ack?'checked':''}>我已核对本人申请信息，所选附件为用于本轮审核的完整版本。</label>`:'<p class="small muted">提交时间：2026年9月22日 09:18<br>回执编号：RC-0922-071</p>'}${state.error?`<div class="inline-error" role="alert">${escape(state.error).replace(/\n/g,'<br>')}</div>`:''}`;
    default:return '';
  }}
  function formPage(){return shell(`<div class="work-area"><aside class="steps" aria-label="申请步骤">${steps.map((name,i)=>`<button class="step ${i===state.step?'active':''}" data-action="step" data-step="${i}" ${i===state.step?'aria-current="step"':''}><span>${name}</span><span class="${stepDone(i)?'done':'todo'}" aria-label="${stepDone(i)?'已填写':'待填写'}">${stepDone(i)?'✓':'·'}</span></button>`).join('')}<div class="form-status">报名状态：<b class="${state.submitted?'ok':''}">${state.submitted?'已提交':'待提交'}</b></div></aside><section class="form-pane">${crumb('申请材料补充',true)}${formContent()}<div class="form-actions">${state.step>0?'<button class="secondary" data-action="prev-step">上一步</button>':''}${state.step<steps.length-1?'<button class="secondary" data-action="save-form">保存草稿</button><button class="primary" data-action="next-step">下一步</button>':state.submitted?'<button class="primary" data-action="route" data-route="status">查看提交回执</button><button class="secondary" data-action="app" data-app="mail">查看邮箱</button>':'<button class="secondary" data-action="save-form">保存草稿</button><button class="primary" data-action="submit">确认提交</button>'}</div></section></div>`);}
  function dashboard(){return shell(`<section class="dashboard"><h2>♧ 申请操作</h2><div class="dashboard-cards">${[['departments','申请院系开放查询','⌕'],['form','填写或修改申请信息','✎'],['status','申请状态查询','⌕'],['result','申请结果查询','⌕']].map(([route,name,symbol])=>`<button class="dashboard-card" data-action="route" data-route="${route}"><span aria-hidden="true">${symbol}</span>${name}</button>`).join('')}</div>${state.survey.result==='C'?'<div class="task-card dashboard-task"><h3>本人待办：补充考核与材料复核</h3><p>资格核验已完成。请查看项目经历补述模板及文字面试安排。</p><button class="primary" data-action="route" data-route="assessment">进入本人任务</button></div>':state.submitted?'<p class="small muted" style="margin-top:33px">本轮申请材料已提交，后续安排以邮件通知为准。</p>':''}</section>`);}
  function departments(){return shell(`<div class="system-inner">${crumb('申请院系开放查询')}<h2 class="page-title">申请院系报名时间及注意事项</h2><div class="table-scroll"><table class="data-table"><thead><tr><th>院系编码</th><th>院系名称</th><th>报名时间</th><th>查看活动通知</th></tr></thead><tbody><tr><td>001</td><td>数学与统计学院</td><td>2026-09-01 至 2026-09-15<br><span class="muted">已结束</span></td><td>—</td></tr><tr><td>028</td><td>自动化学院</td><td>2026-09-01 至 2026-09-18<br><span class="muted">已结束</span></td><td>—</td></tr><tr><td>173</td><td>先进系统研究院</td><td>2026-09-22 至 2026-09-24<br><span class="small muted">本轮仅面向邮件通知的申请人</span></td><td><button class="primary" data-action="route" data-route="notice">查看</button></td></tr></tbody></table></div></div>`);}
  function notice(){return shell(`<div class="system-inner">${crumb('活动通知')}<h2 class="page-title">关于 2027 年研究生招生补充材料确认的通知</h2><p class="small muted">发布单位：先进系统研究院招生办公室　发布日期：2026年9月22日</p><article class="notice-body"><p>部分接收安排尚未确定。已收到本轮邮件的申请人可补交项目说明，继续等待递补机会；未收到邮件的考生无需重复提交。</p><h3>一、材料要求</h3><p>请检查已登记的个人陈述版本，并补交一份项目说明。项目说明应清楚区分本人实际承担的工作与小组共同成果。</p><h3>二、后续安排</h3><p>材料补充完成后，系统将向本人邮箱发送问卷与方向接收进度地址。问卷、接收进度和正式接收结果是不同流程。</p><p>本轮所有材料和页面仅面向本人申请会话开放，请勿代替他人提交或公开他人完整材料。</p></article><div class="form-actions"><button class="primary" data-action="route" data-route="form">返回申请材料补充</button></div></div>`);}
  function status(){return shell(`<div class="system-inner">${crumb('申请状态查询')}<h2 class="page-title">本人申请状态</h2>${state.submitted?`<div class="inline-success">材料确认已完成，已收到本轮申请。</div>${row('姓名','陈言')}${row('报名号','HC2026-0922-071')}${row('申请状态','材料已提交，等待后续考核')}${row('回执编号','RC-0922-071')}${row('提交时间','2026年9月22日 09:18')}${row('专业排名比例',escape(state.form.rank)+'%')}${row('申请方向',escape(state.form.program))}${row('营期批次',escape(state.form.camp))}${row('成绩及排名证明',escape(findFile(state.form.file)?.name||''),'本轮实际提交附件')}<div class="form-actions"><button class="secondary" data-action="save-receipt">保存提交回执</button></div><div class="task-card"><h3>后续安排已发送</h3><p>候补进度查询路径及补充考核后续安排已发送至本人登记邮箱。请自行查收。</p><button class="primary" data-action="app" data-app="mail">打开邮箱</button></div>`:'<div class="info-note">当前申请尚未提交。完成材料核对后，请在“申请信息提交”中确认提交。</div><button class="primary" data-action="route" data-route="form">继续填写</button>'}</div>`);}
  function result(){return shell(`<div class="system-inner">${crumb('申请结果查询')}<h2 class="page-title">申请结果</h2><div class="info-note">暂无接收结果。正式结果以学校发布的拟接收意向及后续审核通知为准。</div>${row('申请人','陈言')}${row('本轮状态',state.submitted?'材料已补充，等待后续安排':'申请材料待补充')}${row('拟接收结果','尚未发布')}</div>`);}
  const surveyQuestions=['任务尚未达到我预期的结果时，即使已经到了原定结束时间，我也很难停下来休息。','当别人进度明显领先时，我通常仍能按照自己的节奏安排任务，不急于追赶。','在同一项任务中连续落后，会让我更想立刻再试一次，直到改变结果。','只要结果已经足够满足自己的目标，我可以接受它不是参与者中最好的。','面对一套持续比我表现更好的系统，我愿意先按它设定的目标调整做法，再判断这个目标是否适合自己。','当评估记录与我的判断相冲突时，我愿意暂时保留分歧，即使这会拖慢下一步安排。','如果一种修正能持续提高我的评分，即使暂时说不清原因，我也愿意先采用它。','即使权威评估认为有必要，我也不愿让对方替我确定“我当时是怎样想的”。','如果我对衡川招生安排的理解与研究院统一说明不同，为了继续申请，我愿意先按统一说明修正自己的判断，再处理原有疑问。','如果获得衡川的补充接收机会需要多轮材料补充与面试复核，并按照招生系统的反馈不断调整回答，我愿意继续，直到系统确认符合要求。'];
  function questionnaire(){if(!state.submitted)return status();const s=state.survey;const options=['非常不同意','比较不同意','不确定／视情况','比较同意','非常同意'];const outcome={A:['A类','你倾向在竞争中主动推进，同时保留自己的判断标准。','常规复核；可以修改答案后重新提交。'],B:['B类','你倾向维持自身节奏，或降低持续竞争中的投入。','常规复核；可以修改答案后重新提交。'],C:['C类匹配','可进入后续安排。','补充考核入口已开放。']}[s.result];return shell(`<div class="system-inner questionnaire-page">${crumb('申请人情况与学习习惯问卷')}<h2 class="page-title">申请人情况与学习习惯问卷</h2><p class="small muted">请根据陈言在故事中的学习与申请习惯作答。提交后可查看后续安排；这不是对现实玩家的心理判断。</p>${s.result?`<div class="inline-success"><b>本次分类：${outcome[0]}。</b><br>${outcome[1]}<br>后续安排：${outcome[2]}<p class="small muted">已保存第 ${s.versions} 版回执。修改并重新提交会保留此前版本。</p>${s.result==='C'?'<button class="primary survey-next" data-action="route" data-route="assessment">进入补充考核与材料复核</button>':''}</div>`:''}<section class="survey-list">${surveyQuestions.map((q,i)=>`<fieldset class="survey-item"><legend><b>${i+1}.</b> ${q}</legend><div>${options.map((label,index)=>`<label><input type="radio" name="survey-${i}" value="${index+1}" data-survey-question="${i}" ${Number(s.answers[i])===index+1?'checked':''}>${index+1} · ${label}</label>`).join('')}</div></fieldset>`).join('')}</section><div class="form-actions"><button class="secondary" data-action="save-survey">保存草稿</button><button class="primary" data-action="submit-survey">提交问卷</button></div></div>`);}
  function assessment(){if(state.survey.result!=='C')return questionnaire();const old=taskAttachments[0],liveCorrected=state.oldAttachmentCorrected;return shell(`<div class="system-inner assessment-page">${crumb('补充考核与材料复核')}<div class="assessment-heading"><div><p class="campus-kicker">本人任务 · MR-0922-071</p><h2 class="page-title">补充考核与材料复核</h2><p>资格核验已完成。请阅读材料模板并准备文字面试；本页不改变当前候补顺位。</p></div><span class="assessment-status">进行中</span></div><div class="assessment-grid"><section class="assessment-card"><span>01</span><h3>资格核验</h3><b class="status-ok">已完成</b><p>推免资格、在读状态与本轮申请材料已经核对。</p></section><section class="assessment-card"><span>02</span><h3>项目经历补述</h3><b>待确认</b><p>请按模板区分本人工作、小组成果与未完成内容。</p></section><section class="assessment-card"><span>03</span><h3>文字面试</h3><b>已安排</b><p>2026年9月23日 09:30—09:50，入口将在开始前开放。</p></section></div><section class="attachment-panel"><div class="attachment-head"><div><h3>任务附件</h3><p>文件清单更新时间：2026年9月22日 10:18</p></div><span>${liveCorrected?'2 个文件 · 已修订':'2 个文件'}</span></div><div class="attachment-row"><div class="file-symbol">PDF</div><div><b>${liveCorrected?'项目经历填写模板（通用版）.pdf':escape(old.name)}</b><small>${liveCorrected?'当前版本 · 2026/09/22 10:21':`当前任务调用 · ${old.servedAt}`}</small></div><div class="attachment-buttons">${liveCorrected?'<button class="secondary" data-action="generic-template">打开</button>':`<button class="primary" data-action="open-assessment-file">打开附件</button>${state.oldAttachmentOpened?`<button class="secondary" data-action="save-assessment-file">${state.oldAttachmentSaved?'已保存副本':'保存副本'}</button>`:''}`}</div></div><div class="attachment-row"><div class="file-symbol doc">DOC</div><div><b>项目经历补述空白表.docx</b><small>2027级推免补充考核通用模板</small></div><button class="secondary" data-action="blank-template">预览</button></div>${liveCorrected?`<div class="version-record"><div><b>本人任务附件版本记录</b><p>10:18 向本任务发送过“项目经历填写示例.pdf”；10:21 经办人员替换为通用版。</p></div><button class="text" data-action="recover-old-example">取回10:18版本</button></div>`:''}</section>${state.oldAttachmentOpened&&!state.tangAsked?'<div class="inquiry-box"><div><h3>附件内容与本任务不一致？</h3><p>可向材料复核经办人唐敏提交附件名称、旧材料编号和页面时间。请勿转发他人的完整材料。</p></div><button class="secondary" data-action="ask-tang">向唐敏询问</button></div>':''}${state.tangInquiryPending?'<div class="loading-line"><i></i><span>正在提交附件核对请求…</span></div>':''}${state.tangAsked?'<div class="inline-success"><b>附件核对请求已受理。</b><br>经办人已更换当前模板；回复已发送至本人邮箱。已保存的旧副本不会被替换。</div>':''}<section class="interview-note"><h3>文字面试说明</h3><ol><li>围绕本人承担的项目工作进行补述，不要求披露他人完整材料。</li><li>回答将作为本轮招生复核材料留存；面试开始前仍可检查本人任务附件。</li><li>面试入口将在预约时段开放，错过后可在当日申请一次改期。</li></ol></section></div>`);}
  function oldArchive(){return `<section class="archive-page"><header class="archive-header"><div><span>衡川大学先进系统研究院</span><h1>历年招生资料归档</h1></div><div class="archive-year">旧站 · 2019—2024</div></header><nav class="archive-nav"><span>招生首页</span><span>夏令营</span><span>推免招生</span><span>历年附件</span><span>迁移说明</span></nav><main class="archive-body"><div class="archive-breadcrumb">首页 &gt; 研究生招生 &gt; 历年资料</div><div class="archive-notice"><b>旧站迁移说明</b><p>本页用于保留历年招生通知及附件索引。部分图片与早期附件正在迁移，缺失内容将分批补录。</p></div><div class="archive-layout"><section><h2>历年招生资料</h2><table class="archive-table"><thead><tr><th>年份</th><th>资料名称</th><th>附件状态</th></tr></thead><tbody><tr><td>2024</td><td>推荐免试研究生接收工作说明</td><td><button class="text" data-action="archive-placeholder">查看附件</button></td></tr><tr><td>2023</td><td>优秀大学生夏令营入营名单及活动安排</td><td><button class="text" data-action="archive-placeholder">名单.pdf</button></td></tr><tr><td>2023</td><td>推荐免试研究生拟接收公示（归档）</td><td><button class="text" data-action="archive-placeholder">公示附件.pdf</button></td></tr><tr><td>2022</td><td>夏令营常见问题与材料模板</td><td><span class="archive-missing">缩略图缺失</span></td></tr><tr><td>2021</td><td>研究生招生专业目录</td><td><button class="text" data-action="archive-placeholder">目录.pdf</button></td></tr></tbody></table><section class="archive-files"><h3>附件区</h3><div><span class="broken-thumb">图片<br>缺失</span><p><b>2023年夏令营活动资料包</b><br><small>部分文件名已迁移，原链接可能失效。</small></p></div><div><span class="broken-thumb file">PDF</span><p><b>2023年推免招生材料汇总</b><br><small>公开公示附件，不含个人申请材料。</small></p></div></section></section><aside><h3>站点说明</h3><p>旧站内容仅供历史查询。2025年后的招生通知请访问研究院新站。</p><h3>常用年份</h3><p>2024　2023　2022　2021</p><h3>资料来源</h3><p>研究生招生办公室历年公开通知与附件索引。</p></aside></div><div class="archive-actions"><button class="secondary" data-action="save-archive-url">${state.archiveUrlSaved?'网址已保留':'保留本页网址'}</button><button class="text" data-action="route" data-route="assessment">返回本人任务</button></div></main><footer class="archive-footer"><span>旧站资料维护 / 当前离线</span><span>最后归档：2024-12-30　|　附件迁移进行中</span></footer></section>`;}
  const progressProfiles={a01:{name:'周亦成',school:'江南信息大学',major:'智能系统方向',project:'课程项目与系统设计'},lzy:{name:'林知远',school:'宁川理工大学',major:'控制系统方向',project:'轮式巡检平台多传感器定位'},a03:{name:'许澄',school:'松岭大学',major:'智能系统方向',project:'创新实践项目'},a04:{name:'邱然',school:'岚江工业大学',major:'控制系统方向',project:'控制实验课程设计'},a05:{name:'顾宁',school:'东浦科技大学',major:'智能系统方向',project:'设备维护与数据采集'},a06:{name:'蒋思齐',school:'北河大学',major:'控制系统方向',project:'信号处理课程项目'},chen:{name:'陈言',school:'岚江工业大学',major:'控制系统方向',project:'移动平台轨迹跟踪'},zhao:{name:'赵可宁',school:'岚江工业大学',major:'控制系统方向',project:'材料待审核'},b03:{name:'程语安',school:'松岭大学',major:'智能系统方向',project:'材料待审核'},b04:{name:'宋惟真',school:'江南信息大学',major:'控制系统方向',project:'材料待审核'}};
  function candidateSummary(){const p=progressProfiles[state.progressCandidate]||progressProfiles.a01;return shell(`<div class="system-inner">${crumb('申请人履历摘要')}<h2 class="page-title">申请人履历摘要</h2><p class="small muted">用于方向接收进度展示；不构成正式录取或学籍信息。</p><div class="profile-sheet"><dl><dt>展示姓名</dt><dd>${escape(p.name)}</dd><dt>本科院校</dt><dd>${escape(p.school)}</dd><dt>申请方向</dt><dd>${escape(p.major)}</dd><dt>项目经历</dt><dd>${escape(p.project)}</dd><dt>材料状态</dt><dd>已纳入本方向进度展示</dd></dl><div class="profile-note"><b>资料说明</b><p>页面字段依据本轮提交材料生成。若展示内容与本人提交材料不一致，请以正式审核通知为准。</p></div></div><div class="form-actions"><button class="secondary" data-action="route" data-route="rank">返回方向接收进度</button></div></div>`);}
  function rank(){if(!state.submitted)return status();const rows=[['1','a01','拟接收展示','2026-09-22 09:12'],['2','lzy','拟接收展示','2026-09-22 09:15'],['3','a03','拟接收展示','2026-09-22 09:12'],['4','a04','拟接收展示','2026-09-22 09:14'],['5','a05','拟接收展示','2026-09-22 09:11'],['6','a06','拟接收展示','2026-09-22 09:13'],['7','chen','候补 · 顺位 1','2026-09-22 09:20'],['8','zhao','候补 · 顺位 2','2026-09-22 09:20'],['9','b03','候补 · 顺位 3','2026-09-22 09:20'],['10','b04','候补 · 顺位 4','2026-09-22 09:20']];return shell(`<div class="system-inner">${crumb('方向接收进度')}<div class="rank-summary"><div><span class="label">候补顺位</span><span class="rank-number">01</span></div><div><h2>陈言，你当前位于候补组第 1 位。</h2><p>方向接收进度会随审核安排更新。<br>更新时间：2026年9月22日 09:20</p></div></div><p class="small muted">本页为方向接收进度，最终结果以正式审核通知为准。</p><div class="table-scroll"><table class="data-table"><thead><tr><th>序号</th><th>姓名</th><th>申请方向</th><th>展示状态</th><th>最近更新</th></tr></thead><tbody>${rows.map(r=>{const p=progressProfiles[r[1]];return `<tr ${r[0]==='7'?'class="me"':''}><td>${r[0]}</td><td><button class="table-link" data-action="candidate-summary" data-candidate="${r[1]}">${escape(p.name)}</button></td><td>${escape(p.major)}</td><td>${r[2]}</td><td>${r[3]}</td></tr>`;}).join('')}</tbody></table></div><p class="small muted" style="line-height:1.9">前六行是本方向当前展示的拟接收名单；候补组的顺位仅在候补申请人之间计算。</p><div class="form-actions"><button class="secondary" data-action="save-rank">保存当前表格副本</button><button class="primary" data-action="route" data-route="forum">查看申请交流区</button></div></div>`);}
  function followup(){return shell(`<div class="system-inner">${crumb('夏令营材料留存')}<h2 class="page-title">七月夏令营材料留存</h2><p class="small muted">本页仅汇总本人留存的营期通知、行程和活动确认文件。</p><div class="task-card"><h3>已登记文件</h3><p>报到与研究院参观、导师交流、项目介绍、招生咨询与活动总结。</p><p>如需核对，请以本人保存的通知、车票和活动确认回执为准。该页面不构成新增考核，也不包含入学后的培养记录。</p><button class="secondary" data-action="files-folder" data-folder="july">打开七月文件</button></div></div>`);}
  function forum(){return `<section class="community-page"><div class="community-head"><span>衡川大学先进系统研究院</span><h1>申请人交流区</h1><p>仅用于流程性问题交流。请勿公开本人完整材料、证件或他人私人通讯。</p></div><div class="community-list"><article class="community-post"><div class="post-meta">赵可宁 · 候补申请人　2026-09-22 09:31</div><h2>同一封补材料通知会有两个版本吗？</h2><p>我的邮件写的是“补交项目说明”，朋友收到的邮件又提到“确认个人陈述版本”。日期和发件地址一样，我不想把整封邮件贴出来。</p><div class="post-reply"><b>陈言</b>　${state.zhaoAdded?'已添加联系方式；请到聊天中由本人主动发起核对。':'我这边也是先核对个人陈述和项目说明。'}<button class="text" data-action="add-zhao" ${state.zhaoAdded?'disabled':''}>${state.zhaoAdded?'已添加联系方式':'添加联系方式，仅核对通知'}</button></div></article><article class="community-post"><div class="post-meta">蒋思齐 · 拟接收展示　2026-09-22 09:29</div><h2>补交文件的命名需要和七月版本一致吗？</h2><p>我保留了夏令营时的文件名，今天只补了一份项目说明。系统回执里能看到附件名，建议先把回执保存下来。</p><button class="text" data-action="files-folder" data-folder="application">查看本人申请材料</button></article><article class="community-post"><div class="post-meta">系统公告　2026-09-22 09:25</div><h2>方向接收进度说明</h2><p>展示名单、候补申请人与正式接收结果属于不同状态。请以本人邮件和后续审核通知为准。</p><button class="secondary" data-action="route" data-route="rank">查看方向接收进度</button></article><article class="community-post"><div class="post-meta">林知远　2026-09-22 09:28</div><h2>项目说明里要写到什么程度？</h2><p>课程项目是小组完成的，我只写自己做过的数据整理和模型验证，应该够了吗？</p><button class="text" data-action="route" data-route="lzyThread">查看讨论串</button></article><article class="community-post"><div class="post-meta">许澄 · 夏令营申请人　2026-09-22 09:27</div><h2>七月的活动回执只写了到场，还需要补别的吗？</h2><p>我理解回执只是活动留存。现在还是按今天这封邮件的材料要求走，别把行程单当作新的审核材料。</p></article><article class="community-post"><div class="post-meta">匿名申请人　2026-09-22 09:26</div><h2>问卷结果是马上出吗？</h2><p>我把和竞争有关的选项都选得很高，结果还是显示常规复核。是不是还会看对统一反馈的接受程度？</p><button class="secondary" data-action="route" data-route="questionnaire">进入本人问卷</button></article></div></section>`;}
  function campusHeader(compact=false){const c=campus(),q=state.campusQuery||'';return `<header class="campus-head ${compact?'compact':''}" style="--campus-accent:${c.accent};--campus-dark:${c.accentDark}"><div class="campus-mark" aria-hidden="true"><span>${c.name.slice(0,1)}</span></div><div class="campus-title"><span>${c.english}</span><h1>${c.name}</h1></div><form data-campus-form><input aria-label="${c.name}站内搜索" data-campus-search value="${escape(q)}" placeholder="搜索新闻、通知、院系、人员"><button class="primary">搜索</button></form></header>`;}
  function campusHome(){const c=campus();return `<section class="campus-page" style="--campus-accent:${c.accent};--campus-dark:${c.accentDark}">${campusHeader()}<nav class="campus-nav"><span>学校概况</span><span>人才培养</span><span>科学研究</span><span>校园生活</span><span>信息公开</span><span>办事服务</span></nav><main class="campus-layout"><section class="campus-feature"><div class="campus-feature-art" aria-hidden="true"><i></i><b></b><em></em></div><div class="campus-feature-copy"><p class="campus-kicker">校园要闻 · 2026.09</p><h2>${c.lead}</h2><p>${c.leadText}</p><button class="text" data-action="campus-search" data-query="${c.lead.slice(0,8)}">查看相关报道</button></div></section><aside class="campus-notices"><div class="campus-section-title"><h2>通知公告</h2><span>更多</span></div>${c.notices.map((item,i)=>`<button class="campus-list-link" data-action="campus-article" data-article="${state.campusKey}-notice-${i}"><span>${item}</span><time>09-${18-i*2}</time></button>`).join('')}</aside><section class="campus-services"><div class="campus-section-title"><h2>常用服务</h2><span>服务大厅</span></div><div class="service-grid">${c.services.map((name,i)=>`<button class="service-tile" data-action="campus-service" data-service="${i}"><b>${name}</b><span>${i===1&&c===campuses.ningchuan?'历史资料与项目归档':c.serviceIntro}</span></button>`).join('')}</div></section><section class="campus-digest"><div class="campus-section-title"><h2>院系动态</h2><span>全部动态</span></div>${c.schools.map((item,i)=>`<button class="campus-digest-link" data-action="campus-article" data-article="${state.campusKey}-digest-${i}"><time>2026.09.${15-i*2}</time><span><b>${item}</b><small>${c.serviceIntro}</small></span></button>`).join('')}</section></main><footer>${c.name} · 校园新闻与信息服务　<span>建议使用站内搜索查找历史内容</span></footer></section>`;}
  function candidateArticle(name){const record=candidateRecords[name];return {id:`candidate-${name}`,category:record.category,title:record.title,summary:record.text,body:`${record.text} 该条目由${candidateCampus[name]===state.campusKey?'本校相关单位':'校际信息交换平台'}按日常事务归档，具体办理方式以所属单位通知为准。`};}
  function homeArticles(){const c=campus(),key=state.campusKey;const notice=c.notices.map((title,i)=>({id:`${key}-notice-${i}`,category:`校园通知 · 2026-09-${18-i*2}`,title,summary:`${c.name}已发布该项日常安排，涉及的具体时间、办理对象和入口以本通知为准。`,body:`${c.name}发布“${title}”。相关服务按照本学期工作安排分批开放，师生可通过${c.services[i%c.services.length]}栏目查询个人状态。${c.leadText} 如有流程问题，请在开放时间内向所属单位咨询。`}));const digest=c.schools.map((title,i)=>({id:`${key}-digest-${i}`,category:`院系动态 · 2026-09-${15-i*2}`,title,summary:`${title}，活动面向校内师生开放，具体报名与现场安排由承办单位发布。`,body:`${c.name}${title}。本次活动围绕秋季教学、学生项目和校园服务展开，参与者可按通知查看时间、地点和准备事项。${c.serviceIntro} 承办单位提醒，公开新闻仅用于活动介绍，不替代个人业务通知。`}));return [...notice,...digest];}
  function articleList(){return campusArticleData[state.campusKey]||[];}
  function findCampusArticle(id){return articleList().find(item=>item.id===id)||homeArticles().find(item=>item.id===id)||Object.keys(candidateCampus).map(candidateArticle).find(item=>item.id===id);}
  function articleResult(item){return `<article><time>${escape(item.category)}</time><h2>${escape(item.title)}</h2><p>${escape(item.summary)}</p><button class="text" data-action="campus-article" data-article="${escape(item.id)}">查看详情</button></article>`;}
  function genericResults(c,q){const exactCandidate=Object.keys(candidateCampus).find(name=>candidateCampus[name]===state.campusKey&&q.includes(name));const general=articleList().filter(item=>item.access!=='internal').slice(0,3);const items=exactCandidate?[candidateArticle(exactCandidate),...general]:general;return items.length?items:[{id:`${state.campusKey}-notice`,category:'校园信息 · 2026-09-18',title:q?`关于“${q}”的相关校园信息`:'2026 年秋季学期校园信息汇总',summary:'相关信息已按院系工作流程归档，具体事项请以所属单位通知为准。',body:'该条目由学校信息服务平台生成，包含公开通知、办事指南和院系动态的索引。'}];}
  function campusSearch(){const c=campus(),q=(state.campusQuery||'').trim();const results=genericResults(c,q);const relevant=c===campuses.ningchuan&&/林知远|巡检|多传感器/.test(q);if(relevant){results.push(...articleList().filter(item=>item.access==='internal'));}return `<section class="campus-page" style="--campus-accent:${c.accent};--campus-dark:${c.accentDark}">${campusHeader(true)}<nav class="campus-nav"><button class="text" data-action="route" data-route="campusHome">首页</button><span>站内搜索</span></nav><main class="campus-search-results"><p class="small muted">${q?`找到与“${escape(q)}”相关的 ${results.length} 条结果`:'请输入关键词搜索校园公开信息'}</p>${results.map(articleResult).join('')}</main></section>`;}
  function campusService(){const c=campus(),index=Math.max(0,Math.min(c.services.length-1,Number(state.campusServiceKey)||0)),name=c.services[index];const ncut=c===campuses.ningchuan&&index===1;return `<section class="campus-page" style="--campus-accent:${c.accent};--campus-dark:${c.accentDark}">${campusHeader(true)}<nav class="campus-nav"><button class="text" data-action="route" data-route="campusHome">首页</button><span>办事服务</span><span>${escape(name)}</span></nav><main class="campus-service-detail"><p class="campus-kicker">${c.name} · 服务大厅</p><h1>${escape(name)}</h1><p class="service-intro">${escape(c.serviceIntro)}</p><div class="service-detail-body"><h2>服务说明</h2><p>${ncut?'科研资料库收录项目阶段报告、实验教学案例和历史学院公告。公开目录可直接检索，部分历史资料需要校内服务码。':'本服务提供线上申请、办事指南和历史记录查询。具体开放时间以当日公告和服务大厅页面为准。'}</p>${ncut?'<div class="service-clue"><b>历史资料库测试入口</b><p>访问码格式：夏令营资料批次 + 归档月份。资料批次中的月份和批次号保持原样，归档月份使用两位数字。</p><p class="small muted">提示：本学期夏令营资料批次可在校内活动回执中查到；历史报道的发布日期即为归档月份线索。</p></div>':'<ul><li>网上提交：全天开放</li><li>线下窗口：工作日 08:30–17:00</li><li>咨询电话：校内服务平台转接</li></ul>'}</div><div class="form-actions"><button class="secondary" data-action="route" data-route="campusHome">返回学校首页</button><button class="primary" data-action="route" data-route="campusSearch">进入站内搜索</button></div></main><footer>${c.name} · 校园新闻与信息服务</footer></section>`;}
  function campusArticle(){const c=campus(),item=findCampusArticle(state.campusArticleId)||articleList()[0];if(!item)return campusSearch();const accessKey=item.id==='nc-project'?'campusAccessProject':item.id==='nc-memorial'?'campusAccessMemorial':'';if(item.access==='internal'&&accessKey&&!state[accessKey]){return `<section class="campus-page" style="--campus-accent:${c.accent};--campus-dark:${c.accentDark}">${campusHeader(true)}<main class="campus-access-panel"><p class="campus-kicker">校内资料库访问</p><h1>${escape(item.title)}</h1><p>该资料属于历史科研资料库，仅限校园网或校内服务码访问。公开目录保留标题和摘要，全文需要验证。</p><form data-campus-access><label for="campus-pass">校内服务码</label><input id="campus-pass" data-campus-pass autocomplete="off" placeholder="请输入服务码"><button class="primary">验证并查看全文</button></form><p class="small muted">服务码说明可在学校“办事服务”栏目中查找。</p><div class="form-actions"><button class="secondary" data-action="route" data-route="campusSearch">返回搜索结果</button><button class="text" data-action="campus-service" data-service="1">查看相关服务说明</button></div></main></section>`;}if(item.id==='nc-project'){state.projectRead=true;state.ncutProjectViewed=true;}if(item.id==='nc-memorial'){state.memorialRead=true;state.ncutMemorialViewed=true;}if(state.ncutProjectViewed&&state.ncutMemorialViewed)state.sourceNoticeSent=true;save();const related=['nc-project','nc-memorial'].includes(item.id)?'<section class="related-material"><b>相关资料</b><p>衡川大学先进系统研究院历年招生资料归档（旧站）</p><button class="text" data-action="route" data-route="oldArchive">查看归档页</button></section>':'';return `<section class="campus-page" style="--campus-accent:${c.accent};--campus-dark:${c.accentDark}"><main class="campus-article-page"><p class="campus-kicker">${escape(item.category)}</p><h1>${escape(item.title)}</h1><div class="campus-article-meta">${c.name} · 校园新闻网　|　公开目录记录日期：${escape(item.category.split('·').pop().trim())}</div><p class="campus-article-lead">${escape(item.summary)}</p>${item.body.split('。').filter(Boolean).map(p=>`<p>${escape(p)}。</p>`).join('')}${related}<div class="form-actions"><button class="secondary" data-action="route" data-route="campusSearch">返回搜索结果</button>${item.access?'<span class="small muted">本篇资料的校内服务码已验证。</span>':''}</div></main><footer>${c.name} · 校园新闻与信息服务</footer></section>`;}
  function ningchuanHome(){state.campusKey='ningchuan';return campusHome();}
  function ningchuanSearch(){state.campusKey='ningchuan';state.campusQuery=state.ncutQuery;return campusSearch();}
  function profile(){const name=state.rosterCorrected?'陆明':'林知远';return shell(`<div class="system-inner">${crumb('候补资料摘要')}<h2 class="page-title">候补资料摘要</h2><p class="small muted">本页仅显示方向接收进度中的公开字段，不提供历史附件。</p><div class="profile-sheet"><dl><dt>姓名</dt><dd>${name}</dd><dt>本科院校 / 院系</dt><dd>宁川理工大学 / 自动化学院</dd><dt>项目经历</dt><dd>轮式巡检平台多传感器定位</dd><dt>项目职责</dt><dd>负责人</dd><dt>交流讨论</dt><dd><button class="table-link" data-action="route" data-route="lzyThread">查看林知远的讨论串</button></dd></dl><div class="profile-note"><b>资料说明</b><p>公开字段来自本轮进度展示。若内容与本人材料不一致，应以正式审核通知和可核验资料为准。</p></div></div><div class="form-actions"><button class="secondary" data-action="route" data-route="rank">返回方向接收进度</button></div></div>`);}
  function newsProject(){state.campusKey='ningchuan';state.campusArticleId='nc-project';return campusArticle();}
  function newsMemorial(){state.campusKey='ningchuan';state.campusArticleId='nc-memorial';return campusArticle();}
  function lzyThread(){return `<section class="thread-page"><header><div class="thread-avatar">林</div><div><h1>林知远</h1><p>申请人交流区会话</p></div></header><div class="thread-messages"><div class="bubble mine">项目说明里，小组项目应该怎么写本人分工？</div>${state.lzyPrompted?`<div class="bubble other"><p>我写了数据整理和模型验证。别把组里别人做的也都写成自己完成的，后面问起来会很麻烦。</p><small>2026-09-22 09:35</small></div>`:''}${state.lzyBatchAsked?'<div class="bubble mine">你也参加过七月夏令营吗？</div><div class="bubble other">参加过，不过接收安排一直没定。你先按自己收到的通知走吧。</div>':''}</div><div class="thread-actions">${!state.lzyPrompted?'<button class="secondary" data-action="lzy-prompt">发送：询问项目说明</button>':''}${state.lzyPrompted&&!state.lzyBatchAsked?'<button class="secondary" data-action="lzy-batch">发送：询问夏令营</button>':''}<p class="small muted">此会话仅显示你主动发送的内容。</p></div></section>`;}
  function identityCheck(){const projectSeen=state.ncutProjectViewed||state.projectRead;const memorialSeen=state.ncutMemorialViewed||state.memorialRead;const ready=projectSeen&&memorialSeen;if(!state.campusAccessProject&&!state.campusAccessMemorial)return shell(`<div class="system-inner">${crumb('资料来源核对')}<h2 class="page-title">资料来源核对</h2><div class="info-note">历史项目资料尚未开放。本页不会展示或下载附件；请先自行搜索宁川理工大学网站，在“科研资料库”完成服务码验证。</div><div class="form-actions"><button class="secondary" data-action="route" data-route="rank">返回方向接收进度</button></div></div>`);return shell(`<div class="system-inner">${crumb('资料来源核对')}<h2 class="page-title">资料来源核对</h2><p class="small muted">仅就公开目录和已验证的历史资料提出问题；不要求提交他人的私人材料。</p>${state.identityReported?`<div class="inline-success"><b>已收到资料来源核对反馈。</b><br>本次提交对象为方向接收进度中的公开字段。候补状态未即时变化。</div><div class="task-card"><h3>处理通知</h3><p>若仍对资料来源存疑，可继续保留本人副本并等待后续安排。</p><button class="primary" data-action="route" data-route="rank">查看方向接收进度</button></div>`:`<div class="task-card"><h3>核对进度</h3><div class="source-check ${projectSeen?'checked':''}">宁川理工大学项目报道：${projectSeen?'已查看':'待查看'}</div><div class="source-check ${memorialSeen?'checked':''}">宁川理工大学学院公告：${memorialSeen?'已查看':'待查看'}</div><label class="form-choice">当前可确认的情况<select data-identity-conclusion><option value="">请选择</option><option value="same">当前展示资料与已故者的院校、项目经历及职责对应，需要说明资料来源。</option><option value="name">仅凭同名，已经确认是同一个人。</option><option value="operator">已经查明关联账号由谁操作。</option></select></label><div class="form-actions"><button class="secondary" data-action="route" data-route="rank">返回方向接收进度</button><button class="primary" data-action="submit-identity" ${ready?'':'disabled'}>提交资料来源疑问</button></div>${!ready?'<p class="small muted">请在服务码验证后，从站内搜索结果查看两条历史资料；姓名本身不足以确认身份。</p>':''}</div>`}</div>`);}
  function login(){return shell(`<section class="login-hero"><div class="campus-art" aria-hidden="true"></div><div class="login-card"><h1>欢迎报考衡川大学</h1><label class="hidden" for="login-project">招生项目</label><select id="login-project"><option>推免生预报名</option><option>硕士研究生招生</option><option>博士研究生招生</option></select><div class="login-help"><b>用户名：报名号；密码：注册时填写的密码。</b><br>请通过推免生预报名系统申请，并如实核对信息。当前电脑已保留本人申请会话。</div><input aria-label="用户名" value="HC2026-0922-071" readonly><input aria-label="密码" type="password" value="retained-session" readonly><button class="primary" data-action="restore-session">恢复当前申请会话</button><div class="login-links"><span>已识别本人邮件链接</span><span>本地会话</span></div></div></section><div class="dashboard"><h2>通知公告</h2><p class="small muted">2027 年研究生招生补充材料确认工作已开始。</p></div>`,true);}
  function browserPage(){const route=currentRoute();const pages={home,form:formPage,dashboard,departments,notice,status,result,rank,candidateSummary,questionnaire,assessment,oldArchive,followup,forum,profile,ningchuanHome,ningchuanSearch,campusHome,campusSearch,campusArticle,campusService,newsProject,newsMemorial,lzyThread,identityCheck,login,blank:()=>'<div class="blank-page">在地址栏输入已获得的网址</div>'};return `<div class="route-frame" data-route="${route}">${(pages[route]||pages.blank)()}</div>`;}
  function browser(){const tab=currentTab();return `<div class="window-tabs">${state.tabs.map((t,i)=>`<div class="browser-tab ${i===state.activeTab?'selected':''}"><button class="text tab-label" data-action="select-tab" data-tab="${i}" style="color:inherit">${escape(routeLabel(t.history[t.index]))}</button>${state.tabs.length>1?`<button class="close-tab" data-action="close-tab" data-tab="${i}" aria-label="关闭标签">×</button>`:''}</div>`).join('')}<button class="new-tab" data-action="new-tab" aria-label="新标签页">＋</button></div><div class="browser-toolbar"><button class="nav-icon" data-action="back" aria-label="后退" ${tab.index===0?'disabled':''}>‹</button><button class="nav-icon" data-action="forward" aria-label="前进" ${tab.index===tab.history.length-1?'disabled':''}>›</button><button class="nav-icon" data-action="refresh" aria-label="刷新">⟳</button><form class="address-box" id="address-form"><span aria-hidden="true">▤</span><input aria-label="浏览器地址栏" id="address" value="${escape(routePath(currentRoute()))}" autocomplete="off" spellcheck="false"></form><button class="nav-icon" data-action="history" aria-label="历史记录" title="历史记录">◷</button></div><div class="browser-content">${browserPage()}</div>`;}
  function downloads(){return state.savedFiles.map(item=>({...item,name:item.name.replace(/\.txt$/i,'.pdf'),size:item.size||'留存副本'}));}
  function findFile(id){return [...files.application,...files.july,...files.reference,...taskAttachments,...downloads()].find(f=>f.id===id);}
  function filesPage(){const folder=['application','july','downloads'].includes(state.folder)?state.folder:'application';const items=folder==='downloads'?downloads():files[folder];const folderName={application:'申请材料',july:'七月夏令营',downloads:'下载与留存'}[folder];return `<div class="app-content files-layout"><aside class="files-sidebar"><h3>陈言的电脑</h3>${[['application','申请材料'],['july','七月夏令营'],['downloads','下载与留存']].map(([id,label])=>`<button class="folder-button ${folder===id?'active':''}" data-action="files-folder" data-folder="${id}">${icon('folder')}<span>${label}</span></button>`).join('')}<button class="folder-button" data-action="app" data-app="note">${icon('note')}<span>备忘录</span></button></aside><section class="files-main"><div class="files-toolbar">此电脑　›　文档　›　${folderName}</div><div class="file-list"><div class="file-table-head"><span>名称</span><span>修改日期</span><span>大小</span></div>${items.length?items.map(file=>`<button class="file-item" data-action="open-file" data-file="${file.id}"><span class="name">${icon('document')}<span>${file.name}</span></span><time>${file.date}</time><span class="size">${file.size}</span></button>`).join(''):'<div class="empty-state">此文件夹为空。<br><span class="small">另存的页面与附件会保存在这里。</span></div>'}</div><div class="file-preview">${items.length} 个项目${folder==='july'?' · 此处为七月已经保存的原始文件。':''}</div></section></div>`;}
  const mails={
    invitation:{sender:'先进系统研究院招生办公室',address:'admission@hcu.example',time:'2026年9月22日 08:06',subject:'关于 2027 年研究生招生补充材料确认的通知',body:()=>'<p>陈言同学：</p><p>您好。部分接收安排尚未确定，符合条件的申请人可以补交材料，继续等待递补机会。</p><p>请核对已登记的个人陈述版本，并补交一份项目说明。七月通知、行程和已整理材料均保留在本人电脑中。</p><button class="primary" data-action="route" data-route="form">进入申请人工作台</button><p class="small muted">https://admission.hcu.example/2027<br>本封邮件已于进入页面前阅读。</p><p>衡川大学先进系统研究院<br>招生办公室</p>'},
    submitted:{sender:'研究生报考服务系统',address:'service@xspt.hcu.example',time:'2026年9月22日 09:20',subject:'材料补充回执、问卷及方向接收进度',body:()=>'<p>陈言同学：</p><p>本轮补充材料已收到，回执编号 RC-0922-071。</p><p>请完成“申请人情况与学习习惯问卷”，并自行查看本方向的接收进度。两项地址仅向本轮申请人开放。</p><div class="form-actions"><button class="primary" data-action="route" data-route="questionnaire">进入问卷</button><button class="secondary" data-action="route" data-route="rank">查看方向接收进度</button></div><p class="small muted">问卷：https://admission.hcu.example/2026/questionnaire<br>进度：https://xspt.hcu.example/sstm/tm/progress</p><p>本页为方向接收进度，最终结果以正式审核通知为准。</p>'},
    followup:{sender:'先进系统研究院教务办公室',address:'teaching@hcu.example',time:'2026年9月22日 09:24',subject:'2027级推免：夏令营活动记录确认',body:()=>'<p>陈言同学：</p><p>为安排后续活动并核对七月营期档案，系统已导入你的到场、分组及活动后复盘条目。该页面仅用于确认档案内容，<b>不属于新增考核，也不用于成绩评定。</b></p><p>请查阅目前显示的记录。若对内容有疑问，可保留本人说明；后续安排将另行通知。</p><button class="primary" data-action="route" data-route="followup">查看夏令营活动记录</button><p class="small muted">任务编号：RV-0922-071<br>来源批次：HC26-JUL-02<br>https://xspt.hcu.example/sstm/tm/revisit/0922</p><p>衡川大学先进系统研究院<br>教务办公室</p>'},
    forum:{sender:'先进系统研究院招生办公室',address:'admission@hcu.example',time:'2026年9月22日 09:29',subject:'2027级补充考核安排与交流区说明',body:()=>'<p>陈言同学：</p><p>您的本人备注已留存。补充考核的具体安排将通过本邮箱通知。</p><p>流程性问题可先查阅申请人交流区。涉及本人材料与记录的异议，请通过本人页面联系经办人员，勿在公共讨论区发布完整材料。</p><button class="primary" data-action="route" data-route="forum">进入申请人交流区</button><p class="small muted">https://admission.hcu.example/2027/community</p><p>先进系统研究院招生办公室</p>'},
    source:{sender:'研究生报考服务系统',address:'service@xspt.hcu.example',time:'2026年9月22日 09:47',subject:'资料来源复核：联合归档读取记录',body:()=>'<p>陈言同学：</p><p>系统检测到你查看的历史校园资料与本方向候补展示字段存在可核对的来源关联。联合归档记录中的读取目的与原始授权范围并不一致。</p><p>如需保留这项资料来源疑问，请只依据已验证的公开全文提交说明；不要提交或猜测账号操作者信息。</p><button class="primary" data-action="route" data-route="identityCheck">进入资料来源核对</button><p class="small muted">关联封存标签：JI-22-014<br>读取回执日期：2026-09-21</p>'},
    correction:{sender:'先进系统研究院招生办公室',address:'admission@hcu.example',time:'2026年9月22日 10:06',subject:'HC-014 展示字段核对结果',body:()=>'<p>陈言同学：</p><p>已收到你对 HC-014 展示资料的反馈。交流资料与本轮资格审核分别维护，我们已完成相关展示字段校正。</p><p>你的候补状态目前没有变化。请继续留意本人考核通知。</p><button class="primary" data-action="route" data-route="rank">查看候补进度</button><p class="small muted">本次核对对象的字段快照已附在你的提交回执中。</p>'},
    attachmentReply:{sender:'唐敏',address:'tangmin@asri.hcu.example',time:'2026年9月22日 10:21',subject:'回复：项目经历填写示例附件核对',body:()=>'<p>陈言同学：</p><p>已核对。任务附件误调用了往届整理版本，现已替换为通用模板。该附件不属于你的申请材料，也不会计入你的考核记录。</p><p>你可以在本人任务的“附件版本记录”中取回系统曾向你发送的版本，用于保留本次核对过程。请勿继续转发其中的个人信息。</p><button class="primary" data-action="route" data-route="assessment">返回材料复核页</button><p class="small muted">经办人：唐敏<br>核对编号：MR-0922-071-A1</p>'}
  };
  function mailPage(){const ids=state.submitted?[(state.tangAsked?'attachmentReply':null),(state.identityReported?'correction':null),(state.sourceNoticeSent?'source':null),(state.savedAnswer?'forum':null),'submitted','invitation'].filter(Boolean):['invitation'];const selected=ids.includes(state.selectedMail)?state.selectedMail:ids[0];const mail=mails[selected];return `<div class="app-content mail-layout"><aside class="mail-nav"><div class="mail-logo">云笺邮箱<div class="mail-account">chenyan@letter.example</div></div><div class="mail-folder">收件箱　${ids.length}</div><p class="small muted" style="padding:8px 12px">已发送</p><p class="small muted" style="padding:8px 12px">草稿箱</p></aside><section class="mail-list"><div class="mail-list-label">收件箱 / 2026年9月22日</div>${ids.map(id=>`<button class="mail-item ${id===selected?'active':''}" data-action="mail" data-mail="${id}"><span class="sender">${!state.readMails.includes(id)?'● ':''}${mails[id].sender}</span><strong>${mails[id].subject}</strong><small>${mails[id].time}</small></button>`).join('')}</section><article class="mail-reading"><h1>${mail.subject}</h1><div class="mail-metadata">发件人：${mail.sender} &lt;${mail.address}&gt;<br>收件人：陈言 &lt;chenyan@letter.example&gt;<br>送达时间：${mail.time}</div><div class="mail-body">${mail.body()}</div></article></div>`;}
  function chatPage(){if(!state.zhaoAdded)return `<div class="app-content chat-layout"><aside class="chat-rail"><div class="chat-avatar">陈</div>${icon('chat')}</aside><aside class="chat-list"><div class="chat-search">⌕　搜索</div><p>暂无会话</p></aside><section class="chat-empty">${icon('chat')}<p>暂无新的消息</p></section></div>`;const messages=state.zhaoMessages||[];const followups=[['材料要求','你的通知里写了哪些材料？','落款是 9 月 22 日 09:20，附件栏只列《项目说明》。我没有收到其他材料要求，所以不敢把七月的文件再传一遍。'],['问卷进度','你问卷提交了吗？','还在做。交流区有人说会进入复核，但这类说法没法确认，先只留好自己的回执。'],['接收进度','你看到方向接收进度了吗？','看到了，我在候补第 2 位。页面里是普通的公开展示信息，先别根据名单推断什么。']];const ready=state.zhaoConversationStarted&&!state.zhaoTyping&&state.zhaoQuestionStage<followups.length;return `<div class="app-content chat-layout"><aside class="chat-rail"><div class="chat-avatar">陈</div>${icon('chat')}</aside><aside class="chat-list"><div class="chat-search">⌕　搜索</div><button class="chat-contact active"><span class="chat-avatar other">赵</span><span><b>赵可宁</b><small>${state.zhaoConversationStarted?'在线':'已添加，暂无消息'}</small></span></button></aside><section class="chat-conversation"><header>赵可宁 <small>仅你们可见</small></header><div class="thread-messages">${messages.length?messages.map(m=>`<div class="bubble ${m.side}">${escape(m.text)}</div>`).join(''): '<div class="chat-quiet">你已添加赵可宁。她还没有发来消息。</div>'}${state.zhaoTyping?'<div class="typing-indicator"><i></i><i></i><i></i><span>赵可宁正在输入…</span></div>':''}</div>${ready?`<div class="chat-followups"><span>可继续询问</span><button class="secondary" data-action="zhao-question" data-question="${state.zhaoQuestionStage}">${followups[state.zhaoQuestionStage][1]}</button></div>`:''}<form class="chat-composer" data-zhao-chat><textarea data-zhao-message aria-label="发送给赵可宁的消息" placeholder="输入任意内容，发起一次核对…" ${state.zhaoTyping?'disabled':''}></textarea><button class="primary" ${state.zhaoTyping?'disabled':''}>发送</button></form></section></div>`;}
  function memoFindings(){const rows=[];if(!state.submitted)rows.push('新通知：先补交《项目说明》。');if(state.submitted)rows.push('材料已提交；问卷和方向接收进度已开放。');if(state.rankViewed)rows.push('已看过方向接收进度；候补名单已记下。');if(state.assessmentOpened)rows.push('C型后续任务：补充考核与材料复核，文字面试安排在9月23日。');if(state.oldAttachmentOpened)rows.push('任务附件异常：当前清单10:18调用了2023年林知远的旧材料，编号 HC23-XLY-B17-042。');if(state.oldAttachmentSaved)rows.push('旧附件副本已保存；之后网页修订不会覆盖本地留存。');if(state.tangAsked)rows.push('唐敏回复“误调用往届版本”，并替换了当前模板。');if(state.archiveUrlSaved)rows.push('已保留研究院旧招生归档地址；页脚当前显示维护离线。');if(state.ncutProjectViewed&&!state.ncutMemorialViewed)rows.push('宁川历史资料：已读 1 / 2。');if(state.ncutProjectViewed&&state.ncutMemorialViewed)rows.push('线索留存：JI-22-014 的外部读取目的写为“招生材料一致性复核”。');if(state.sourceNoticeSent)rows.push('邮箱新增“资料来源复核”通知。');return rows.length?`<section class="memo-findings"><span>当前记录</span>${rows.map(row=>`<p>${escape(row)}</p>`).join('')}</section>`:'';}
  function memoTasks(){const done=Object.values(state.checklist).filter(Boolean).length;return `<section class="memo-checklist" aria-label="待办清单"><div class="memo-list-heading"><div><span class="memo-eyebrow">9月22日 · 今天</span><h2>${state.sourceNoticeSent?'先把已经发现的资料记下来。':'先把手头的材料弄好。'}</h2></div><span class="memo-count">${done} / 4</span></div><div class="memo-tasks">${checklistItems.map(([key,label])=>`<label class="memo-task ${state.checklist[key]?'is-done':''}"><input type="checkbox" data-checklist="${key}" ${state.checklist[key]?'checked':''}><span>${label}</span></label>`).join('')}</div>${memoFindings()}${state.memoEggSeen?`<button class="memo-fold" data-action="memo-egg"><span>夹在清单后面的纸条</span><small>7月10日 · 写给九月的自己</small><span aria-hidden="true">↗</span></button>`:'<p class="memo-tip">完成流程后会自动更新；也可以手动划掉待办。</p>'}</section>`;}
  function notePage(){return `<div class="notepad-toolbar"><span>备忘录</span><div><button class="text" data-action="export-memo">导出当前备忘录 PDF</button><span id="note-save-status">已保存</span></div></div><div class="memo-layout"><div id="memo-tasks">${memoTasks()}</div><section class="memo-writing"><label for="memo">随手记</label><textarea class="notepad-area" id="memo" aria-label="备忘录正文" spellcheck="false" placeholder="想记下的事情……">${escape(state.note)}</textarea></section></div><div class="notepad-status">仅保存在这台电脑 · 待办勾选与随手记分别保存</div>`;}
  function render(){if(!state.entered){$('#app').innerHTML=home();if(!state.openingClosed&&!$('#dialog-root').innerHTML)opening();return;}
    const appNames={browser:'浏览器',files:'文件',mail:'邮箱',chat:'即时通讯',note:'备忘录'};
    const appIcons={browser:'browser',files:'folder',mail:'mail',chat:'chat',note:'note'};
    const contents={browser,files:filesPage,mail:mailPage,chat:chatPage,note:notePage};
    $('#app').innerHTML=`<div class="desktop"><section class="window" aria-label="${appNames[state.activeApp]}">${state.activeApp!=='browser'?`<header class="window-titlebar"><span class="title-name">${icon(appIcons[state.activeApp])}<span>${appNames[state.activeApp]}</span></span><div class="window-controls" aria-hidden="true"><span>—</span><span>□</span></div></header>`:''}<div class="app-frame" data-app="${state.activeApp}">${contents[state.activeApp]()}</div></section><nav class="taskbar" aria-label="桌面应用"><span class="task-day">陈言的电脑</span>${Object.keys(appNames).map(app=>`<button class="task-app ${state.activeApp===app?'active':''}" data-action="app" data-app="${app}" title="${appNames[app]}" aria-label="${appNames[app]}">${icon(appIcons[app])}<span class="task-label">${appNames[app]}</span>${app==='mail'&&state.submitted&&state.readMails.length<3?'<i class="unread-dot"></i>':''}</button>`).join('')}<button class="task-clock" data-action="calendar" aria-label="日期及本地进度">${state.submitted?'09:24':'09:12'}<br>2026/09/22</button></nav></div>`;
    if(state.activeApp!=='browser')document.querySelectorAll('.title-name svg').forEach(el=>{el.style.width='16px';el.style.height='16px';});
  }
  function documentContent(file,entry,compact=false){
    const images=entry.tickets||entry.pages;
    return `<div class="pdf-toolbar"><span>${entry.tickets?'车票图片 · 往返两张':`PDF · ${entry.pages.length} 页`} · ${entry.size}</span><div><button class="secondary" data-action="zoom-document">放大阅读</button><a class="secondary" href="${entry.pdf}" target="_blank" rel="noopener">打开 PDF</a><a class="primary" href="${entry.pdf}" download="${escape(file.name)}">下载 PDF</a></div></div><div class="pdf-pages ${entry.tickets?'ticket-pages':''}" tabindex="0" aria-label="${escape(file.name)}页面预览">${images.map((src,i)=>`<figure><img src="${src}" alt="${escape(file.name)}${entry.tickets?(i===0?'去程车票':'返程车票'):`第${i+1}页`}" ${i?'loading="lazy"':''}><figcaption>${entry.tickets?(i===0?'去程 · 2026年7月11日':'返程 · 2026年7月13日'):`第 ${i+1} 页 / 共 ${images.length} 页`}</figcaption></figure>`).join('')}</div><details class="pdf-text"><summary>查看文字内容</summary><pre>${escape(entry.text)}</pre></details>${compact?'':`<div class="doc-meta">本地文件 · ${escape(file.date)}${file.id==='july-note'?' · 七月原始留存，只读':''}</div>`}`;
  }
  async function showFile(id,supplied){const file=supplied||findFile(id);if(!file)return;
    if(file.photo){modal(`<h2>${escape(file.name)}</h2><div class="pdf-toolbar"><span>JPEG · ${file.width} × ${file.height} · ${escape(file.size)}</span><div><a class="secondary" href="${escape(file.image)}" target="_blank" rel="noopener">查看原图</a><a class="primary" href="${escape(file.image)}" download="${escape(file.name)}">下载照片</a></div></div><figure class="camp-photo-view"><img src="${escape(file.image)}" width="${file.width}" height="${file.height}" alt="七月报到当天拍摄的研究院北楼，树木与广场后的教学科研楼"><figcaption><span>先进系统研究院 · 北楼</span><time>2026.07.11 09:32</time></figcaption></figure><pre class="photo-note">${escape(file.text)}</pre>`,'document-dialog photo-dialog',file.name);return;}
    modal(`<h2>${escape(file.name)}</h2><div id="document-body" data-document-id="${escape(id)}"><p class="document-loading">正在打开文档……</p></div>`,'document-dialog pdf-dialog',file.name);
    try{const entry=file.pdf?file:await window.DibuPDF.fromText(file);const body=$('#document-body');
      if(!body||body.dataset.documentId!==id){if(entry.temporary)URL.revokeObjectURL(entry.pdf);return;}
      activeDocument=entry;body.innerHTML=documentContent(file,entry);
    }catch(error){const body=$('#document-body');if(body)body.innerHTML='<p>文档暂时未能打开，请关闭后重试。</p>';console.error('Document export failed',error);}
  }
  function picker(){modal(`<h2>选择项目说明</h2><p class="small muted">此电脑 / 文档 / 申请材料 · 请确认文件只陈述本人实际承担的工作。</p><div class="picker-layout"><div class="file-picker">${files.application.filter(f=>['application-log','statement'].includes(f.id)).map(f=>`<div class="picker-item"><label><input type="radio" name="attachment" value="${f.id}" ${state.form.file===f.id?'checked':''}><span><strong>${f.name}</strong><br><small>${f.date} · ${f.size}</small></span></label><button class="text small" type="button" data-action="preview-picker-file" data-file="${f.id}">查看内容</button></div>`).join('')}</div><div id="picker-preview"><p class="picker-placeholder">点击“查看内容”，在这里翻阅完整 PDF。</p></div></div><div class="dialog-actions"><button class="secondary" data-action="close-dialog">取消</button><button class="primary" data-action="choose-file">选择</button></div>`,'picker-dialog','选择项目说明');}
  function submit(){const f=state.form;const errors=[];if(f.file!=='application-log')errors.push('请在申请材料中选择《项目说明》。');if(!f.ack)errors.push('请确认项目说明与本人实际经历一致。');if(errors.length){state.error=errors.join('\n');save();render();return;}
    modal('<h2>确认提交补充材料</h2><p class="form-text">本次将提交陈言的《项目说明》。提交后进入本轮招生审核，后续安排通过登记邮箱通知。</p><div class="dialog-actions"><button class="secondary" data-action="close-dialog">返回核对</button><button class="primary" data-action="confirm-submit">确认提交</button></div>','','确认提交');
  }
  function saveCopy(id,name,text){name=name.replace(/\.txt$/i,'.pdf');if(!state.savedFiles.some(f=>f.id===id))state.savedFiles.push({id,name,text,date:'2026/09/22 09:24'});save();toast('已保存至“文件 / 下载与留存”。');}
  function saveTaskAttachment(){const source=taskAttachments[0];if(!state.savedFiles.some(f=>f.id==='saved-old-project-example'))state.savedFiles.push({...source,id:'saved-old-project-example',name:'项目经历填写示例_10时18分留存.pdf',date:'2026/09/22 10:19'});state.oldAttachmentSaved=true;save();toast('10:18版本已保存至“文件 / 下载与留存”。');}
  const actions={
    'close-dialog':closeDialog,
    enter(){state.entered=true;state.openingClosed=true;state.activeApp='browser';state.tabs=[{history:['home','form'],index:1}];state.activeTab=0;state.step=0;save();render();},
    route(el){go(el.dataset.route);},
    app(el){state.activeApp=el.dataset.app;if(state.activeApp==='mail'&&!state.readMails.includes(state.selectedMail))state.readMails.push(state.selectedMail);save();render();},
    step(el){state.step=Number(el.dataset.step);state.error='';save();render();},
    'next-step'(){state.step=Math.min(steps.length-1,state.step+1);save();render();},
    'prev-step'(){state.step=Math.max(0,state.step-1);save();render();},
    'save-form'(){save();toast('申请信息已保存为草稿。');},
    'save-survey'(){save();toast('问卷草稿已保存。');},
    'submit-survey'(){const a=state.survey.answers.map(Number);const missing=a.map((v,i)=>v?0:i+1).filter(Boolean);if(missing.length){toast(`请完成第 ${missing.join('、')} 题后再提交。`);return;}const D=a[0]+(6-a[1])+a[2]+(6-a[3]),E=a[4]+(6-a[5])+a[6]+(6-a[7]);state.survey.result=D>=16&&E>=16&&a[8]>=4&&a[9]>=4?'C':D>=16?'A':'B';if(state.rankViewed)state.checklist.notice=true;state.survey.versions+=1;save();render();toast('问卷已提交，回执已保留。');},
    'candidate-summary'(el){state.progressCandidate=el.dataset.candidate;save();go('candidateSummary');},
    'open-campus'(el){state.campusKey=el.dataset.campus;state.campusQuery='';save();go('campusHome');},
    'files-folder'(el){state.folder=el.dataset.folder;if(state.folder==='july')state.checklist.july=true;state.activeApp='files';save();render();},
    'open-file'(el){showFile(el.dataset.file);},
    'open-assessment-file'(){state.oldAttachmentOpened=true;save();render();showFile('old-project-example');},
    'save-assessment-file'(){saveTaskAttachment();render();},
    'recover-old-example'(){saveTaskAttachment();render();},
    'generic-template'(){modal('<h2>项目经历填写模板（通用版）</h2><div class="template-preview"><p><b>1. 项目名称与时间</b></p><p><b>2. 本人承担的具体工作</b></p><p><b>3. 小组共同成果</b></p><p><b>4. 尚未完成或无法核实的内容</b></p><p class="small muted">当前通用版不含往届申请人信息。</p></div>','document-dialog','通用模板');},
    'blank-template'(){modal('<h2>项目经历补述空白表</h2><div class="template-preview"><p>项目名称：________________________</p><p>项目时间：________________________</p><p>本人承担的工作：__________________</p><p>小组共同成果：____________________</p><p>补充说明：________________________</p></div>','document-dialog','空白表预览');},
    'ask-tang'(){if(state.tangInquiryPending||state.tangAsked)return;state.tangInquiryPending=true;save();render();setTimeout(()=>{state.tangInquiryPending=false;state.tangAsked=true;state.oldAttachmentCorrected=true;state.selectedMail='attachmentReply';save();render();toast('唐敏已回复，当前附件已更换。');},1100);},
    'archive-placeholder'(el){const label=el.textContent.trim();toast('正在读取旧站附件…');setTimeout(()=>modal(`<h2>${escape(label)}</h2><div class="archive-file-preview"><p>公开附件索引已找到。</p><p>旧站迁移后部分页面图像尚未恢复，当前只保留文件名、年份和公开归档说明。</p><p class="small muted">该附件不包含个人申请材料；完整文件将在迁移完成后恢复。</p></div>`,'document-dialog','旧站附件'),650);},
    'save-archive-url'(){state.archiveUrlSaved=true;saveCopy('old-archive-address','研究院旧招生归档_网址留存.txt','研究院旧招生归档网址留存\n\n网址：https://archive.asri.hcu.example/admission/\n取得时间：2026年9月22日 10:34\n页面状态：旧站资料维护 / 当前离线\n\n备注：页面含2019—2024年普通夏令营、推免招生及历年附件索引；部分缩略图和附件正在迁移。');render();},
    picker,
    'zoom-document'(el){const pages=el.closest('.pdf-toolbar').nextElementSibling;pages.classList.toggle('zoomed');el.textContent=pages.classList.contains('zoomed')?'适应窗口':'放大阅读';},
    'memo-egg'(){modal('<div class="memo-egg-paper"><span>7月10日 · 写给九月的自己</span><h2>等这些方框都打上勾，</h2><p>如果还没有结果，就先去吃顿热饭。</p><p>还有，别因为终于有人肯要你，<br>就把自己的每一个疑问都划掉。</p><div class="memo-egg-sign">陈言</div></div>','memo-egg-dialog','夹在清单后面的纸条');},
    'export-memo'(){const items=checklistItems.map(([key,label])=>`${state.checklist[key]?'☑':'☐'} ${label}`).join('\n');showFile('memo-export',{id:'memo-export',name:'备忘录_当前快照.pdf',date:'2026/09/22 '+(state.submitted?'09:24':'09:12'),text:'今日待办\n'+items+'\n\n随手记\n'+state.note});},
    'preview-picker-file'(el){const f=findFile(el.dataset.file);$('#picker-preview').innerHTML=documentContent(f,f,true);},
    'choose-file'(){const selected=$('input[name="attachment"]:checked');if(!selected){toast('请先选择一个材料版本。');return;}state.form.file=selected.value;save();closeDialog();render();toast('材料已选定，最终提交前仍可更换。');},
    submit,
    'confirm-submit'(){state.submitted=true;state.checklist.info=true;state.error='';save();closeDialog();render();toast('补充材料已提交。邮箱有新的通知。');},
    mail(el){state.selectedMail=el.dataset.mail;if(!state.readMails.includes(state.selectedMail))state.readMails.push(state.selectedMail);save();render();},
    transcript(){state.transcriptOpen=!state.transcriptOpen;save();render();},
    'save-answer'(){if(!state.recoveryAnswer){toast('请先选择本人目前的确认情况。');return;}state.savedAnswer=true;const version=state.savedFiles.filter(f=>f.id.startsWith('my-revisit-note')).length+1;saveCopy(`my-revisit-note-${version}`,`夏令营活动记录_本人说明_RV-0922-071_${version}.txt`,`夏令营活动记录本人说明（本地留存）\n任务：RV-0922-071\n记录对象：陈言\n来源批次：HC26-JUL-02\n2026年9月22日\n版本：${version}\n\n${state.recoveryAnswer}\n\n说明按本人实际选择原样保存，此副本不修改之前保存的版本。`);state.selectedMail='forum';save();render();toast('本人说明已保存。邮箱收到交流区说明。');},
    'save-receipt'(){if(!state.submitted)return;saveCopy('submission-receipt','提交回执_RC-0922-071.txt',`本轮申请材料提交回执\n来源：https://xspt.hcu.example/sstm/tm/status\n取得时间：2026年9月22日 09:24\n提交时间：2026年9月22日 09:18\n回执编号：RC-0922-071\n\n申请人：陈言\n报名号：HC2026-0922-071\n申请状态：材料已提交，等待后续考核\n专业排名比例：${state.form.rank}%\n申请方向：${state.form.program}\n营期批次：${state.form.camp}\n成绩及排名证明：${findFile(state.form.file)?.name||''}\n\n上述字段与附件版本为本轮实际提交内容。`);},
    'save-rank'(){state.checklist.proof=true;saveCopy('progress-copy-0920','方向接收进度_2026-09-22_0920.txt','来源：https://xspt.hcu.example/sstm/tm/progress\n取得时间：2026年9月22日 09:24\n页面更新时间：2026年9月22日 09:20\n\n方向接收进度\n1 周亦成 拟接收展示\n2 林知远 拟接收展示\n3 许澄 拟接收展示\n4 邱然 拟接收展示\n5 顾宁 拟接收展示\n6 蒋思齐 拟接收展示\n7 陈言 候补顺位1\n8 赵可宁 候补顺位2\n9 程语安 候补顺位3\n10 宋惟真 候补顺位4\n\n本页为方向接收进度，最终结果以正式审核通知为准。');},
    'save-transcript'(){saveCopy('transcript-copy','夏令营活动记录_C-04_文字与来源.txt','来源：https://xspt.hcu.example/sstm/tm/revisit/0922\n取得时间：2026年9月22日 09:24\n任务：RV-0922-071\n条目编号：C-04\n来源批次：HC26-JUL-02\n归档日期：2026年7月13日\n记录对象：陈言\n\n陈言：我当时没有看到有人要求停止。\n\n页面说明：本条目为营期活动后复盘的导入片段，不代表完整访谈，也不代表后续招生考核回答。');},
    'open-reference'(el){const id=el.dataset.file;const granted=id==='ningchuan-project'?state.campusAccessProject:id==='ningchuan-memorial'?state.campusAccessMemorial:false;if(!granted){toast('请先在宁川理工大学“科研资料库”完成本篇服务码验证。');return;}if(id==='ningchuan-project'){state.projectRead=true;state.ncutProjectViewed=true;}if(id==='ningchuan-memorial'){state.memorialRead=true;state.ncutMemorialViewed=true;}save();showFile(id);},
    'campus-article'(el){state.campusArticleId=el.dataset.article;save();go('campusArticle');},
    'campus-service'(el){state.campusServiceKey=el.dataset.service||'0';save();go('campusService');},
    'campus-access'(){const value=($('#campus-pass')?.value||'').trim().toUpperCase(),codes={'nc-project':'JUL-02-11','nc-memorial':'JUL-02-06'},keys={'nc-project':'campusAccessProject','nc-memorial':'campusAccessMemorial'},required=codes[state.campusArticleId],key=keys[state.campusArticleId];if(!required||value!==required){toast('服务码无效，请根据办事服务说明核对格式。');return;}state[key]=true;save();render();toast('本篇资料的校内服务码验证通过。');},
    'ncut-search'(el){const requested=(el.dataset.query||document.querySelector('[data-ncut-search]')?.value||'').trim();state.ncutQuery=requested;state.campusKey='ningchuan';state.campusQuery=requested;save();go('campusSearch');},
    'campus-search'(el){const requested=(el.dataset.query||document.querySelector('[data-campus-search]')?.value||'').trim();state.campusQuery=requested;if(state.campusKey==='ningchuan')state.ncutQuery=requested;save();go('campusSearch');},
    'add-zhao'(){state.zhaoAdded=true;save();render();toast('已添加赵可宁。她不会收到你的材料副本。');},
    'zhao-question'(el){const followups=[['材料要求','你的通知里写了哪些材料？','落款是 9 月 22 日 09:20，附件栏只列《项目说明》。我没有收到其他材料要求，所以不敢把七月的文件再传一遍。'],['问卷进度','你问卷提交了吗？','还在做。交流区有人说会进入复核，但这类说法没法确认，先只留好自己的回执。'],['接收进度','你看到方向接收进度了吗？','看到了，我在候补第 2 位。页面里是普通的公开展示信息，先别根据名单推断什么。']];const q=followups[Number(el.dataset.question)];if(!q||state.zhaoTyping)return;state.zhaoMessages.push({side:'mine',text:q[1]});state.zhaoTyping=true;save();render();setTimeout(()=>{state.zhaoMessages.push({side:'other',text:q[2]});state.zhaoQuestionStage+=1;state.zhaoTyping=false;save();render();},850);},
    'lzy-prompt'(){state.lzyPrompted=true;save();render();},
    'lzy-batch'(){state.lzyBatchAsked=true;save();render();},
    'lzy-identity'(){state.lzyIdentityAsked=true;save();render();},
    'submit-identity'(){if(!((state.ncutProjectViewed||state.projectRead)&&(state.ncutMemorialViewed||state.memorialRead))){toast('请先核对两份来源独立的公开资料。');return;}if(state.identityConclusion!=='same'){toast(state.identityConclusion==='name'?'姓名本身不足以确认身份，请核对院系、项目和职责。':'现有资料不足以确认账号操作者，请仅提交可证实的资料来源疑问。');return;}state.identityReported=true;state.rosterCorrected=true;saveCopy('identity-check-receipt','资料来源核对回执_HC-014.txt','资料来源核对回执\n来源：https://admission.hcu.example/2027/records/check\n提交时间：2026年9月22日 10:02\n核对对象：HC-014\n\n提交时展示字段快照\n姓名：林知远\n本科院校 / 院系：宁川理工大学 / 自动化学院\n项目经历：轮式巡检平台多传感器定位\n项目职责：负责人\n关联交流账号：LZY-014\n\n本人说明：当前展示资料与已故者的院校、项目经历及职责对应，需要说明资料来源。\n\n系统回执：已收到资料来源疑问。候补资格状态不因本次提交即时变化。');state.selectedMail='correction';save();render();toast('资料来源疑问已提交。邮箱收到处理通知。');},
    back(){const tab=currentTab();if(tab.index>0)tab.index--;save();render();},
    forward(){const tab=currentTab();if(tab.index<tab.history.length-1)tab.index++;save();render();},
    refresh(){save();render();toast('页面已刷新。');},
    'new-tab'(){if(state.tabs.length>=5){toast('最多保留5个标签页。');return;}state.tabs.push({history:['blank'],index:0});state.activeTab=state.tabs.length-1;save();render();},
    'select-tab'(el){state.activeTab=Number(el.dataset.tab);save();render();},
    'close-tab'(el){if(state.tabs.length===1)return;const i=Number(el.dataset.tab);state.tabs.splice(i,1);if(state.activeTab>i)state.activeTab--;else if(state.activeTab>=state.tabs.length)state.activeTab=state.tabs.length-1;save();render();},
    history(){const items=[...new Set(state.tabs.flatMap(t=>t.history))].filter(r=>r!=='blank');modal(`<h2>浏览历史</h2><div class="history-list">${items.map(r=>`<button data-action="history-route" data-route="${r}">${routeLabel(r)}<small>${routePath(r)}</small></button>`).join('')}</div>`,'','浏览历史');},
    'history-route'(el){closeDialog();go(el.dataset.route);},
    account(){modal('<h2>申请账户</h2><p class="form-text">申请人：陈言<br>报名号：HC2026-0922-071<br>登记邮箱：chenyan@letter.example<br>验证来源：本人补充考核邮件链接</p>','','申请账户');},
    'restore-session'(){go('form');},
    calendar(){modal('<h2>2026年9月22日 · 星期二</h2><p class="form-text">当前进度已保存在这台电脑的浏览器中。<br>关闭页面后可继续。</p><div class="dialog-actions"><button class="secondary" data-action="reset-prompt">重新开始本段</button><button class="primary" data-action="close-dialog">返回</button></div>','','本地进度');},
    'reset-prompt'(){modal('<h2>重新开始本段</h2><p class="form-text">这会清除本浏览器中本段的申请草稿、提交进度、备忘录与留存副本。</p><div class="dialog-actions"><button class="secondary" data-action="close-dialog">取消</button><button class="primary" data-action="reset">确认重新开始</button></div>','','重新开始确认');},
    reset(){state=JSON.parse(JSON.stringify(defaultState));try{localStorage.removeItem(KEY);}catch{}$('#dialog-root').innerHTML='';render();}
  };
  document.addEventListener('click',event=>{const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const action=actions[el.dataset.action];if(action){event.preventDefault();action(el);}});
  document.addEventListener('input',event=>{const el=event.target;if(el.id==='memo'){state.note=el.value;save();$('#note-save-status').textContent='已保存';}else if(el.dataset.field){state.form[el.dataset.field]=el.type==='checkbox'?el.checked:el.value;save();}else if(el.hasAttribute('data-survey-question')){state.survey.answers[Number(el.dataset.surveyQuestion)]=Number(el.value);state.survey.result='';save();}else if(el.hasAttribute('data-recovery')){state.recoveryAnswer=el.value;state.savedAnswer=false;$('.saved-note')?.remove();save();}else if(el.hasAttribute('data-identity-conclusion')){state.identityConclusion=el.value;save();}});
  document.addEventListener('change',event=>{const el=event.target;if(el.dataset.checklist){
    const key=el.dataset.checklist;if(!checklistItems.some(([id])=>id===key))return;
    state.checklist[key]=el.checked;
    const reveal=!state.memoEggSeen&&checklistItems.every(([id])=>state.checklist[id]);
    if(reveal)state.memoEggSeen=true;save();$('#memo-tasks').innerHTML=memoTasks();
    document.querySelector(`[data-checklist="${key}"]`)?.focus();
    if(reveal){toast('清单翻到最后，露出一张旧纸条。');actions['memo-egg']();}return;
  }if(el.dataset.field){state.form[el.dataset.field]=el.type==='checkbox'?el.checked:el.value;save();}if(el.hasAttribute('data-survey-question')){state.survey.answers[Number(el.dataset.surveyQuestion)]=Number(el.value);state.survey.result='';save();}if(el.hasAttribute('data-recovery')){state.recoveryAnswer=el.value;state.savedAnswer=false;$('.saved-note')?.remove();save();}if(el.hasAttribute('data-identity-conclusion')){state.identityConclusion=el.value;save();}});
  document.addEventListener('submit',event=>{if(event.target.hasAttribute('data-zhao-chat')){event.preventDefault();const input=event.target.querySelector('[data-zhao-message]');const message=(input?.value||'').trim();if(!message){toast('输入任意一句话即可发起核对。');return;}if(state.zhaoTyping)return;state.zhaoMessages.push({side:'mine',text:message});state.zhaoConversationStarted=true;state.zhaoTyping=true;save();render();setTimeout(()=>{state.zhaoMessages.push({side:'other',text:'我在。先只核对日期和文件名，不传完整材料；这样至少不会把彼此的申请信息留在交流区。'});state.zhaoTyping=false;save();render();},950);return;}if(event.target.hasAttribute('data-campus-access')){event.preventDefault();actions['campus-access']();return;}if(event.target.hasAttribute('data-ncut-form')||event.target.hasAttribute('data-campus-form')){event.preventDefault();const query=(event.target.querySelector('[data-campus-search],[data-ncut-search]')?.value||'').trim();state.campusQuery=query;if(state.campusKey==='ningchuan')state.ncutQuery=query;save();go('campusSearch');return;}if(event.target.id!=='address-form')return;event.preventDefault();const value=$('#address').value.trim().replace(/\/$/,'');const campusMatch=Object.entries(campuses).find(([,c])=>value===c.name||value.includes(c.domain));if(campusMatch){state.campusKey=campusMatch[0];state.campusQuery='';if(campusMatch[0]==='ningchuan')state.ncutQuery='';save();go('campusHome');return;}const route=Object.entries(paths).find(([,path])=>path&&path.replace(/\/$/,'')===value);if(route){if(['rank','questionnaire'].includes(route[0])&&!state.submitted){toast('请先完成本人材料补充。');return;}go(route[0]);}else{toast('未找到该地址，请核对已经获得的完整网址。');}});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&$('#dialog-root').innerHTML)closeDialog();if(event.key==='Tab'&&$('#dialog-root').innerHTML){const focusable=[...$('#dialog-root').querySelectorAll('button:not([disabled]),input,select,textarea,a[href]')];const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});
  render();
})();
